"""
installer/backend/pipewire.py
==============================
PipeWire / JACK configuration for MAP2 low-latency audio.

Educational note on PipeWire quantum:
  PipeWire's 'quantum' is the number of audio samples processed per callback.
  It is the direct equivalent of JACK's 'period' and ALSA's 'period_size'.
  Lower quantum = lower latency but higher CPU load and higher dropout risk.

  The quantum is set at RUNTIME via:
    pw-metadata -n settings 0 clock.force-quantum <N>
    pw-metadata -n settings 0 clock.force-rate <Hz>

  We deliberately do NOT set force-quantum in pipewire.conf.d because that
  blocks runtime overrides.  The systemd service ExecStartPre handles this.

  See: MEMORY.md — "DO NOT set force-quantum in pipewire.conf.d"
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from .executor import CommandExecutor, CommandResult

logger = logging.getLogger("installer.pipewire")

# The sole PipeWire config fragment for MAP2 (only this file should exist)
PIPEWIRE_CONF_DIR  = Path.home() / ".config" / "pipewire" / "pipewire.conf.d"
PIPEWIRE_CONF_FILE = PIPEWIRE_CONF_DIR / "99-map2-audio-latency.conf"

PIPEWIRE_CONF_TEMPLATE = """\
# MAP2 Audio Platform — PipeWire low-latency configuration
# Generated by MAP2 installer — do not edit manually.
#
# IMPORTANT: force-quantum is intentionally NOT set here.
# It is set at runtime by the map2-backend.service ExecStartPre commands:
#   pw-metadata -n settings 0 clock.force-rate {sample_rate}
#   pw-metadata -n settings 0 clock.force-quantum {buffer_size}
# This allows runtime overrides without restarting PipeWire.
#
# Educational note: Setting force-quantum here would "lock" PipeWire
# to the value at startup, preventing the service from adjusting it.

context.properties = {{
  # Default clock rate — must match MAP2's sample_rate setting
  default.clock.rate = {sample_rate}

  # Minimum quantum (safety floor — PipeWire won't go below this)
  # Set to our target buffer size so PipeWire doesn't negotiate lower.
  default.clock.min-quantum = {buffer_size}

  # Maximum quantum (ceiling — prevents PipeWire from going too high)
  default.clock.max-quantum = 8192

  # Allow PipeWire clients to request rate/quantum changes
  core.daemon = true
  link.max-buffers = 16
}}
"""


class PipeWireConfig:
    """Write and manage the MAP2 PipeWire configuration fragment."""

    def __init__(self, executor: CommandExecutor):
        self.executor = executor

    def write_config(self, buffer_size: int, sample_rate: int) -> CommandResult:
        """
        Write the 99-map2-audio-latency.conf fragment.

        Idempotent: if the file already exists with the same content,
        it is not rewritten (avoids unnecessary pipewire restarts).
        """
        content = PIPEWIRE_CONF_TEMPLATE.format(
            buffer_size=buffer_size,
            sample_rate=sample_rate,
        )

        if not self.executor.dry_run:
            PIPEWIRE_CONF_DIR.mkdir(parents=True, exist_ok=True)
            # Only write if content changed (idempotency)
            if PIPEWIRE_CONF_FILE.exists():
                existing = PIPEWIRE_CONF_FILE.read_text()
                if existing == content:
                    logger.info("PipeWire conf unchanged — skipping write.")
                    return CommandResult(0, "unchanged", "", False, [])
            PIPEWIRE_CONF_FILE.write_text(content)
            logger.info("Wrote PipeWire config: %s", PIPEWIRE_CONF_FILE)
        else:
            logger.info("[DRY-RUN] Would write PipeWire config to %s", PIPEWIRE_CONF_FILE)

        return CommandResult(0, str(PIPEWIRE_CONF_FILE), "", self.executor.dry_run,
                             ["write", str(PIPEWIRE_CONF_FILE)])

    def set_runtime_quantum(self, buffer_size: int, sample_rate: int) -> list[CommandResult]:
        """
        Apply the quantum at runtime via pw-metadata.

        Must set rate FIRST, then quantum (order matters for PipeWire).
        This is idempotent — setting the same quantum twice is harmless.
        """
        results = []
        # Rate must be set before quantum (PipeWire constraint)
        results.append(self.executor.run([
            "pw-metadata", "-n", "settings", "0",
            "clock.force-rate", str(sample_rate)
        ]))
        results.append(self.executor.run([
            "pw-metadata", "-n", "settings", "0",
            "clock.force-quantum", str(buffer_size)
        ]))
        return results

    def restart_pipewire(self) -> list[CommandResult]:
        """Restart PipeWire user services to apply config changes."""
        services = ["pipewire", "pipewire-pulse", "wireplumber"]
        results = []
        for svc in services:
            results.append(self.executor.run(
                ["systemctl", "--user", "restart", f"{svc}.service"]
            ))
        return results
