export enum PluginType {
  None = '',
  InvalidPlugin = 'InvalidPlugin',
  NamPlugin = 'NamPlugin',
  Plugin = 'Plugin',
  AllpassPlugin = 'AllpassPlugin',
  AmplifierPlugin = 'AmplifierPlugin',
  AnalyserPlugin = 'AnalyserPlugin',
  BandpassPlugin = 'BandpassPlugin',
  ChorusPlugin = 'ChorusPlugin',
  CombPlugin = 'CombPlugin',
  CompressorPlugin = 'CompressorPlugin',
  ConstantPlugin = 'ConstantPlugin',
  ConverterPlugin = 'ConverterPlugin',
  DelayPlugin = 'DelayPlugin',
  DistortionPlugin = 'DistortionPlugin',
  DynamicsPlugin = 'DynamicsPlugin',
  EQPlugin = 'EQPlugin',
  EnvelopePlugin = 'EnvelopePlugin',
  ExpanderPlugin = 'ExpanderPlugin',
  FilterPlugin = 'FilterPlugin',
  FlangerPlugin = 'FlangerPlugin',
  FunctionPlugin = 'FunctionPlugin',
  GatePlugin = 'GatePlugin',
  GeneratorPlugin = 'GeneratorPlugin',
  HighpassPlugin = 'HighpassPlugin',
  InstrumentPlugin = 'InstrumentPlugin',
  LimiterPlugin = 'LimiterPlugin',
  LowpassPlugin = 'LowpassPlugin',
  MixerPlugin = 'MixerPlugin',
  ModulatorPlugin = 'ModulatorPlugin',
  MultiEQPlugin = 'MultiEQPlugin',
  OscillatorPlugin = 'OscillatorPlugin',
  ParaEQPlugin = 'ParaEQPlugin',
  PhaserPlugin = 'PhaserPlugin',
  PitchPlugin = 'PitchPlugin',
  ReverbPlugin = 'ReverbPlugin',
  SimulatorPlugin = 'SimulatorPlugin',
  SpatialPlugin = 'SpatialPlugin',
  SpectralPlugin = 'SpectralPlugin',
  UtilityPlugin = 'UtilityPlugin',
  WaveshaperPlugin = 'WaveshaperPlugin',
  PiPedalAmpsNode = 'PiPedalAmpsNode',
  SplitA = 'SplitA',
  SplitB = 'SplitB',
  SplitMix = 'SplitMix',
  SplitLR = 'SplitLR',
  ErrorPlugin = 'ErrorPlugin',
  Terminal = 'Terminal',
}

interface PluginGlyph {
  label: string
  tone: string
}

const DEFAULT_GLYPH: PluginGlyph = {
  label: 'FX',
  tone: 'var(--cds-icon-primary, #525252)',
}

const GLYPHS: Partial<Record<PluginType, PluginGlyph>> = {
  [PluginType.AmplifierPlugin]: { label: 'AMP', tone: '#8a3ffc' },
  [PluginType.AnalyserPlugin]: { label: 'ANA', tone: '#0f62fe' },
  [PluginType.ChorusPlugin]: { label: 'CHR', tone: '#6929c4' },
  [PluginType.CompressorPlugin]: { label: 'CMP', tone: '#198038' },
  [PluginType.DelayPlugin]: { label: 'DLY', tone: '#0f62fe' },
  [PluginType.DistortionPlugin]: { label: 'DST', tone: '#d12771' },
  [PluginType.EQPlugin]: { label: 'EQ', tone: '#1192e8' },
  [PluginType.FilterPlugin]: { label: 'FLT', tone: '#005d5d' },
  [PluginType.FlangerPlugin]: { label: 'FLG', tone: '#7f3ae0' },
  [PluginType.GatePlugin]: { label: 'GTE', tone: '#198038' },
  [PluginType.GeneratorPlugin]: { label: 'GEN', tone: '#9f1853' },
  [PluginType.InstrumentPlugin]: { label: 'INS', tone: '#8a3800' },
  [PluginType.LimiterPlugin]: { label: 'LIM', tone: '#9f1853' },
  [PluginType.MixerPlugin]: { label: 'MIX', tone: '#525252' },
  [PluginType.ModulatorPlugin]: { label: 'MOD', tone: '#a56eff' },
  [PluginType.NamPlugin]: { label: 'NAM', tone: '#ee538b' },
  [PluginType.PhaserPlugin]: { label: 'PHS', tone: '#a56eff' },
  [PluginType.PitchPlugin]: { label: 'PIT', tone: '#ba4e00' },
  [PluginType.ReverbPlugin]: { label: 'REV', tone: '#5e32ca' },
  [PluginType.SimulatorPlugin]: { label: 'SIM', tone: '#8a3ffc' },
  [PluginType.SpatialPlugin]: { label: 'SPC', tone: '#4589ff' },
  [PluginType.SplitA]: { label: 'A', tone: '#0f62fe' },
  [PluginType.SplitB]: { label: 'B', tone: '#24a148' },
  [PluginType.SplitLR]: { label: 'LR', tone: '#525252' },
  [PluginType.SplitMix]: { label: 'MX', tone: '#525252' },
  [PluginType.Terminal]: { label: 'CLI', tone: '#161616' },
  [PluginType.UtilityPlugin]: { label: 'UTL', tone: '#525252' },
}

export function getPluginGlyph(pluginType: PluginType): PluginGlyph {
  return GLYPHS[pluginType] ?? DEFAULT_GLYPH
}
