"""Deployment-mode authority (T2431-E) + projection header spec (T2431-F).

Replaces the four-mirror scatter
(``/etc/guitarfx-mode.conf``, ``~/.map2/deployment.json``,
``/etc/map2/environment``, systemd mode drop-ins) with a single canonical
source of truth at ``/etc/map2/mode.json`` and a drift-detecting doctor.

Contract:

* **Authority file**: ``/etc/map2/mode.json`` — operator-editable, written
  atomically with a deterministic header-bearing payload. Every other
  store is a generated projection.
* **Projection file**: ``/etc/map2/environment`` — systemd ``EnvironmentFile=``
  target. Generated from the authority on every mode change and on
  ``DeploymentModeDoctor.repair()``. Carries a machine-readable header
  (T2431-F) with authority-source checksum, generator version, and a
  manual-edit warning.
* **Doctor**: compares the authority file against every projection and
  reports drift or missing artifacts. ``repair()`` regenerates projections
  from the authority (never the other way around).

The legacy ``DeploymentConfig`` class is left intact for now — T2431-E
ships the authority, T2431-J wires the doctor into a CLI / API, and a
later subtask retires the mirrors once every consumer reads through
``get_deployment_mode_authority()``.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from app.paths import Map2Paths

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# T2431-F — projection header standard
# ---------------------------------------------------------------------------

PROJECTION_HEADER_VERSION = 1
"""Bumped when the header format changes in a backwards-incompatible way."""

_ENVIRONMENT_PROJECTION_COMMENT_PREFIX = "#"

# Fields every generated projection carries:
# - schema_version: integer, bumps when the header format changes.
# - generator: human-readable name of the code that produced the file.
# - generator_version: git-ish / release string (best-effort).
# - authority_source: path to the authority file the projection was derived from.
# - authority_checksum_sha256: hex digest of the authority file contents at
#   generation time. Doctors use this to detect authority-vs-projection drift.
# - generated_at: ISO-8601 UTC timestamp.
# - warning: human-readable "do not hand-edit" line.


@dataclass
class ProjectionHeader:
    """Machine-readable header for every generated projection file."""

    authority_source: str
    authority_checksum_sha256: str
    generator: str
    generator_version: str = "1.0.0"
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    schema_version: int = PROJECTION_HEADER_VERSION
    warning: str = (
        "This file is generated by MAP2 from the authority source above. "
        "Do not hand-edit — run `map2 authority doctor --repair` or the "
        "relevant MAP2 mode command instead. Manual edits will be overwritten."
    )

    def to_metadata_dict(self) -> Dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "generator": self.generator,
            "generator_version": self.generator_version,
            "authority_source": self.authority_source,
            "authority_checksum_sha256": self.authority_checksum_sha256,
            "generated_at": self.generated_at,
            "warning": self.warning,
        }

    def to_shell_comment_block(self) -> str:
        """Render the header as a block of ``#``-prefixed comment lines.

        Suitable for sysv-style env files (``/etc/map2/environment``) that are
        consumed as ``systemd EnvironmentFile=`` — systemd ignores comments.
        """
        meta = self.to_metadata_dict()
        lines = [
            f"{_ENVIRONMENT_PROJECTION_COMMENT_PREFIX} === MAP2 generated projection (T2431-F v{meta['schema_version']}) ===",
            f"{_ENVIRONMENT_PROJECTION_COMMENT_PREFIX} warning: {meta['warning']}",
            f"{_ENVIRONMENT_PROJECTION_COMMENT_PREFIX} generator: {meta['generator']} {meta['generator_version']}",
            f"{_ENVIRONMENT_PROJECTION_COMMENT_PREFIX} authority_source: {meta['authority_source']}",
            f"{_ENVIRONMENT_PROJECTION_COMMENT_PREFIX} authority_checksum_sha256: {meta['authority_checksum_sha256']}",
            f"{_ENVIRONMENT_PROJECTION_COMMENT_PREFIX} generated_at: {meta['generated_at']}",
            f"{_ENVIRONMENT_PROJECTION_COMMENT_PREFIX} ===",
        ]
        return "\n".join(lines) + "\n"

    @classmethod
    def parse_shell_header(cls, text: str) -> Optional["ProjectionHeader"]:
        """Read a projection's header out of a shell env file.

        Returns None when the file has no MAP2 projection header — that is
        how ``DeploymentModeDoctor`` detects unmanaged / hand-edited files.
        """
        lines = text.splitlines()
        marker_open = any(line.startswith("# === MAP2 generated projection") for line in lines)
        if not marker_open:
            return None
        fields: Dict[str, str] = {}
        for line in lines:
            if not line.startswith(_ENVIRONMENT_PROJECTION_COMMENT_PREFIX):
                continue
            stripped = line.lstrip("# ").strip()
            for key in (
                "warning",
                "generator",
                "authority_source",
                "authority_checksum_sha256",
                "generated_at",
            ):
                prefix = f"{key}:"
                if stripped.startswith(prefix):
                    fields[key] = stripped[len(prefix):].strip()
                    break
        required = {"authority_source", "authority_checksum_sha256", "generator", "generated_at"}
        if not required.issubset(fields):
            return None
        generator_value = fields.get("generator", "")
        parts = generator_value.rsplit(" ", 1)
        if len(parts) == 2:
            generator_name, generator_version = parts
        else:
            generator_name, generator_version = generator_value, "0.0.0"
        return cls(
            authority_source=fields["authority_source"],
            authority_checksum_sha256=fields["authority_checksum_sha256"],
            generator=generator_name,
            generator_version=generator_version,
            generated_at=fields["generated_at"],
            warning=fields.get("warning", ""),
            schema_version=PROJECTION_HEADER_VERSION,
        )


def compute_sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def atomic_write_bytes(path: Path, data: bytes) -> None:
    """Write ``data`` atomically, creating parent dirs as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


# ---------------------------------------------------------------------------
# T2431-E — deployment-mode authority
# ---------------------------------------------------------------------------

CANONICAL_MODES: Tuple[str, ...] = (
    "ALL-IN-ONE",
    "AUDIO-NODE",
    "CONTROL-NODE",
    "FRONTEND-ONLY",
)

MODE_SYNONYMS: Dict[str, str] = {
    "ALL-IN-ONE": "ALL-IN-ONE",
    "ALL_IN_ONE": "ALL-IN-ONE",
    "ALLINONE": "ALL-IN-ONE",
    "AUDIO": "AUDIO-NODE",
    "AUDIO-NODE": "AUDIO-NODE",
    "AUDIO_NODE": "AUDIO-NODE",
    "MANAGEMENT": "CONTROL-NODE",
    "CONTROL": "CONTROL-NODE",
    "CONTROL-NODE": "CONTROL-NODE",
    "CONTROL_NODE": "CONTROL-NODE",
    "FRONTEND": "FRONTEND-ONLY",
    "FRONTEND-ONLY": "FRONTEND-ONLY",
    "FRONTEND_ONLY": "FRONTEND-ONLY",
}


def canonicalize_mode(value: str) -> str:
    """Normalize any of the historical mode strings to the canonical form."""
    key = (value or "").strip().upper().replace(" ", "-")
    if key in MODE_SYNONYMS:
        return MODE_SYNONYMS[key]
    raise ValueError(f"Unknown deployment mode: {value!r} (expected one of {CANONICAL_MODES})")


def deployment_mode_authority_path() -> Path:
    """Canonical authority path — ``/etc/map2/mode.json`` by default.

    Honors ``Map2Paths.host_config_dir()`` so a test or dev env override
    redirects the whole tree at once.
    """
    return Map2Paths.host_mode_json_path()


def environment_projection_path() -> Path:
    """Generated systemd EnvironmentFile target."""
    return Map2Paths.host_environment_path()


GENERATOR_NAME = "map2-deployment-authority"
GENERATOR_VERSION = "1.0.0"


@dataclass
class DeploymentAuthorityPayload:
    """Contents of ``mode.json`` — the canonical authority file."""

    mode: str  # Canonical (e.g. "ALL-IN-ONE")
    updated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    set_by: Optional[str] = None  # operator / process id, best-effort
    notes: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "schema_version": 1,
            "mode": self.mode,
            "updated_at": self.updated_at,
            "set_by": self.set_by,
            "notes": self.notes,
        }

    def to_json_bytes(self) -> bytes:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True).encode("utf-8")

    @classmethod
    def from_json_bytes(cls, payload: bytes) -> "DeploymentAuthorityPayload":
        data = json.loads(payload.decode("utf-8"))
        mode = canonicalize_mode(str(data.get("mode") or ""))
        return cls(
            mode=mode,
            updated_at=str(data.get("updated_at") or datetime.now(timezone.utc).isoformat()),
            set_by=data.get("set_by"),
            notes=data.get("notes"),
        )


class DeploymentModeAuthorityError(RuntimeError):
    """Raised when the authority file is missing, unreadable, or malformed."""


class DeploymentModeAuthority:
    """Reader / writer for ``/etc/map2/mode.json``."""

    def __init__(self, authority_path: Optional[Path] = None) -> None:
        self._path = authority_path or deployment_mode_authority_path()

    @property
    def path(self) -> Path:
        return self._path

    # -- read --------------------------------------------------------------

    def exists(self) -> bool:
        return self._path.is_file()

    def read(self) -> DeploymentAuthorityPayload:
        if not self.exists():
            raise DeploymentModeAuthorityError(
                f"Deployment-mode authority file missing: {self._path}"
            )
        try:
            raw = self._path.read_bytes()
            return DeploymentAuthorityPayload.from_json_bytes(raw)
        except (OSError, ValueError) as exc:
            raise DeploymentModeAuthorityError(
                f"Deployment-mode authority file unreadable: {self._path}: {exc}"
            ) from exc

    def read_or_default(self, default_mode: str = "ALL-IN-ONE") -> DeploymentAuthorityPayload:
        try:
            return self.read()
        except DeploymentModeAuthorityError:
            return DeploymentAuthorityPayload(mode=canonicalize_mode(default_mode))

    def read_checksum(self) -> str:
        """SHA-256 of the authority file bytes, or empty string when missing."""
        if not self.exists():
            return ""
        try:
            return compute_sha256(self._path.read_bytes())
        except OSError:
            return ""

    # -- write -------------------------------------------------------------

    def write(self, mode: str, *, set_by: Optional[str] = None, notes: Optional[str] = None) -> DeploymentAuthorityPayload:
        canonical = canonicalize_mode(mode)
        payload = DeploymentAuthorityPayload(mode=canonical, set_by=set_by, notes=notes)
        atomic_write_bytes(self._path, payload.to_json_bytes())
        logger.info("Deployment authority updated to %s at %s", canonical, self._path)
        return payload


# ---------------------------------------------------------------------------
# Projection generators
# ---------------------------------------------------------------------------

def render_environment_projection(payload: DeploymentAuthorityPayload, *, authority_path: Path, authority_checksum: str) -> bytes:
    """Render the ``/etc/map2/environment`` projection for systemd.

    The body is a small set of ``KEY=VALUE`` lines derived entirely from
    the authority payload. Every line above the body is a header comment
    so systemd ignores the metadata but operators and the doctor can read
    it.
    """
    header = ProjectionHeader(
        authority_source=str(authority_path),
        authority_checksum_sha256=authority_checksum,
        generator=GENERATOR_NAME,
        generator_version=GENERATOR_VERSION,
    )
    body_lines = [
        f"MAP2_DEPLOYMENT_MODE={payload.mode}",
    ]
    body = "\n".join(body_lines) + "\n"
    return (header.to_shell_comment_block() + body).encode("utf-8")


def write_environment_projection(authority: DeploymentModeAuthority) -> Path:
    """Regenerate the environment projection from the authority file."""
    payload = authority.read()
    checksum = authority.read_checksum()
    rendered = render_environment_projection(
        payload,
        authority_path=authority.path,
        authority_checksum=checksum,
    )
    target = environment_projection_path()
    atomic_write_bytes(target, rendered)
    logger.info("Wrote environment projection %s (mode=%s)", target, payload.mode)
    return target


# ---------------------------------------------------------------------------
# Doctor — drift detection + repair
# ---------------------------------------------------------------------------

@dataclass
class DriftFinding:
    kind: str  # "missing_authority" | "missing_projection" | "header_missing" | "checksum_mismatch" | "stale_header" | "unmanaged_projection"
    target: str
    detail: str
    repairable: bool


@dataclass
class DoctorReport:
    authority_exists: bool
    authority_mode: Optional[str]
    authority_checksum: str
    findings: List[DriftFinding] = field(default_factory=list)

    @property
    def healthy(self) -> bool:
        return self.authority_exists and not self.findings

    def to_dict(self) -> Dict[str, Any]:
        return {
            "authority_exists": self.authority_exists,
            "authority_mode": self.authority_mode,
            "authority_checksum_sha256": self.authority_checksum,
            "healthy": self.healthy,
            "findings": [
                {
                    "kind": finding.kind,
                    "target": finding.target,
                    "detail": finding.detail,
                    "repairable": finding.repairable,
                }
                for finding in self.findings
            ],
        }


class DeploymentModeDoctor:
    """Verify authority <-> projection agreement, and repair projections."""

    def __init__(self, authority: Optional[DeploymentModeAuthority] = None) -> None:
        self._authority = authority or DeploymentModeAuthority()

    @property
    def authority(self) -> DeploymentModeAuthority:
        return self._authority

    def check(self) -> DoctorReport:
        findings: List[DriftFinding] = []

        if not self._authority.exists():
            return DoctorReport(
                authority_exists=False,
                authority_mode=None,
                authority_checksum="",
                findings=[
                    DriftFinding(
                        kind="missing_authority",
                        target=str(self._authority.path),
                        detail="No authority file; defaults will be used at boot.",
                        repairable=False,  # authority must be created by installer/operator
                    )
                ],
            )

        try:
            payload = self._authority.read()
        except DeploymentModeAuthorityError as exc:
            return DoctorReport(
                authority_exists=True,
                authority_mode=None,
                authority_checksum="",
                findings=[
                    DriftFinding(
                        kind="missing_authority",
                        target=str(self._authority.path),
                        detail=f"Authority unreadable: {exc}",
                        repairable=False,
                    )
                ],
            )

        checksum = self._authority.read_checksum()

        # Environment projection
        env_path = environment_projection_path()
        if not env_path.exists():
            findings.append(
                DriftFinding(
                    kind="missing_projection",
                    target=str(env_path),
                    detail="Environment projection absent; regenerate with --repair.",
                    repairable=True,
                )
            )
        else:
            try:
                text = env_path.read_text(encoding="utf-8")
            except OSError as exc:
                findings.append(
                    DriftFinding(
                        kind="missing_projection",
                        target=str(env_path),
                        detail=f"Environment projection unreadable: {exc}",
                        repairable=True,
                    )
                )
            else:
                header = ProjectionHeader.parse_shell_header(text)
                if header is None:
                    findings.append(
                        DriftFinding(
                            kind="header_missing",
                            target=str(env_path),
                            detail=(
                                "Environment projection has no MAP2 header — "
                                "likely hand-edited or pre-T2431-E. Repair will "
                                "overwrite it from the authority."
                            ),
                            repairable=True,
                        )
                    )
                elif header.authority_checksum_sha256 != checksum:
                    findings.append(
                        DriftFinding(
                            kind="checksum_mismatch",
                            target=str(env_path),
                            detail=(
                                f"Projection checksum {header.authority_checksum_sha256[:12]}…"
                                f" does not match current authority {checksum[:12]}…; "
                                "authority has changed since projection was written."
                            ),
                            repairable=True,
                        )
                    )
                else:
                    # Check the body mode actually matches.
                    if f"MAP2_DEPLOYMENT_MODE={payload.mode}" not in text:
                        findings.append(
                            DriftFinding(
                                kind="stale_header",
                                target=str(env_path),
                                detail="Header checksum matches but body mode line is missing.",
                                repairable=True,
                            )
                        )

        return DoctorReport(
            authority_exists=True,
            authority_mode=payload.mode,
            authority_checksum=checksum,
            findings=findings,
        )

    def repair(self) -> DoctorReport:
        """Regenerate every repairable projection from the authority."""
        report = self.check()
        if not report.authority_exists:
            return report
        # Any repairable finding → rewrite the projection.
        if any(f.repairable for f in report.findings):
            write_environment_projection(self._authority)
            # Re-check to confirm convergence.
            return self.check()
        return report


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------

_default_authority: Optional[DeploymentModeAuthority] = None


def get_deployment_mode_authority() -> DeploymentModeAuthority:
    """Return the process-wide authority singleton (lazily constructed)."""
    global _default_authority
    if _default_authority is None:
        _default_authority = DeploymentModeAuthority()
    return _default_authority


def reset_deployment_mode_authority(path: Optional[Path] = None) -> DeploymentModeAuthority:
    """Test hook — override the process-wide authority file location."""
    global _default_authority
    _default_authority = DeploymentModeAuthority(authority_path=path)
    return _default_authority


def resolve_deployment_mode(
    *,
    authority: Optional[DeploymentModeAuthority] = None,
    env_override: Optional[str] = None,
    fallback: str = "ALL-IN-ONE",
) -> str:
    """Return the canonical deployment-mode string (T2437).

    Precedence:
      1. `env_override` — an explicit arg wins. Callers pass this when
         they want to honor `MAP2_DEPLOYMENT_MODE` at call time.
      2. `MAP2_DEPLOYMENT_MODE` env var — operator override at boot.
      3. Authority file at `/etc/map2/mode.json`.
      4. Legacy `~/.map2/deployment.json` — last-resort backwards compat.
      5. `fallback` — when none of the above yields a value.

    The returned value is always canonicalized. Unknown/malformed values
    fall through to the next layer; the final `fallback` is guaranteed
    to be a valid canonical mode.
    """
    if env_override:
        try:
            return canonicalize_mode(env_override)
        except ValueError:
            logger.warning("Ignoring invalid env_override=%r", env_override)

    raw_env = os.environ.get("MAP2_DEPLOYMENT_MODE")
    if raw_env:
        try:
            return canonicalize_mode(raw_env)
        except ValueError:
            logger.warning("Ignoring invalid MAP2_DEPLOYMENT_MODE=%r", raw_env)

    auth = authority or get_deployment_mode_authority()
    if auth.exists():
        try:
            return auth.read().mode
        except DeploymentModeAuthorityError as exc:
            logger.warning("Deployment authority file unreadable, falling back: %s", exc)

    # Legacy fallback — the ~/.map2/deployment.json mirror will be
    # retired in T2437 phase 2 once operator flows stop writing it.
    try:
        from app.deployment.deployment import get_deployment_config

        legacy = get_deployment_config()
        if legacy is not None:
            try:
                return canonicalize_mode(legacy.mode.value)
            except ValueError:
                pass
    except Exception as exc:  # pragma: no cover — defensive
        logger.debug("Legacy DeploymentConfig lookup failed during mode resolve: %s", exc)

    return canonicalize_mode(fallback)
