import type { CelestialPreset } from './types'

export const CELESTIAL_PRESETS: CelestialPreset[] = [
  // ============================================================
  // PIONEERS & EARLY ELECTRIC (Pre-1970)
  // ============================================================
  {
    id: 'les_paul',
    name: 'Les Paul',
    era: 'Pioneers',
    eraGroup: 'pioneers',
    year: 1952,
    topology: 'varimu',
    description: 'Fairchild limiters on multi-track tape bounce. Gentle ratio, slow release, tube warmth compounding with each overdub layer.',
    confidence: 'B',
    referenceAlbums: ['How High the Moon', 'Vaya Con Dios'],
    params: { threshold: -18, ratio: 2, attack: 15, release: 800, knee: 12, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'chuck_berry',
    name: 'Chuck Berry',
    era: 'Pioneers',
    eraGroup: 'pioneers',
    year: 1955,
    topology: 'opto',
    description: 'Chess Studios tube console. Gentle opto compression — transients punch through, sustained bends evened out.',
    confidence: 'B',
    referenceAlbums: ['Johnny B. Goode', 'Roll Over Beethoven'],
    params: { threshold: -20, ratio: 3, attack: 25, release: 500, knee: 10, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'scotty_moore',
    name: 'Scotty Moore',
    era: 'Pioneers',
    eraGroup: 'pioneers',
    year: 1956,
    topology: 'opto',
    description: 'Sun Studio valve chain. Slap-back echo interacted with compression — repeated signal creates pumping sustain.',
    confidence: 'B',
    referenceAlbums: ["That's All Right", 'Mystery Train'],
    params: { threshold: -22, ratio: 2.5, attack: 20, release: 600, knee: 8, makeupGain: 5, autoMakeup: false },
  },
  {
    id: 'link_wray',
    name: 'Link Wray',
    era: 'Pioneers',
    eraGroup: 'pioneers',
    year: 1958,
    topology: 'fet',
    description: 'Deliberately distorted tone — FET-style fast clamping on shredded waveform, adding sustain to the fuzz.',
    confidence: 'C',
    referenceAlbums: ['Rumble'],
    params: { threshold: -15, ratio: 8, attack: 0.5, release: 150, knee: 3, makeupGain: 6, autoMakeup: false },
  },
  {
    id: 'chet_atkins',
    name: 'Chet Atkins',
    era: 'Pioneers',
    eraGroup: 'pioneers',
    year: 1960,
    topology: 'opto',
    description: 'RCA Studio B. Opto smoothed dynamic range of complex fingerstyle without killing percussive nail attack.',
    confidence: 'B',
    referenceAlbums: ['Yakety Axe', 'Mr. Sandman'],
    params: { threshold: -24, ratio: 2, attack: 30, release: 400, knee: 14, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'wes_montgomery',
    name: 'Wes Montgomery',
    era: 'Pioneers',
    eraGroup: 'pioneers',
    year: 1963,
    topology: 'varimu',
    description: 'Rudy Van Gelder studio. Thumb-picked octave technique — vari-mu adds subtle tube saturation and levels dynamic range.',
    confidence: 'B',
    referenceAlbums: ['The Incredible Jazz Guitar', "Bumpin'"],
    params: { threshold: -20, ratio: 1.5, attack: 20, release: 1000, knee: 16, makeupGain: 2, autoMakeup: false },
  },
  {
    id: 'george_harrison',
    name: 'George Harrison',
    era: 'Pioneers',
    eraGroup: 'pioneers',
    year: 1966,
    topology: 'fet',
    description: 'Abbey Road RS124 and Fairchild units. "Taxman" — aggressive FET compression clips transient for nasal, mid-forward sound.',
    confidence: 'A',
    referenceAlbums: ['Revolver', 'Abbey Road'],
    params: { threshold: -16, ratio: 8, attack: 1, release: 200, knee: 4, makeupGain: 5, autoMakeup: false },
  },
  {
    id: 'jimi_hendrix',
    name: 'Jimi Hendrix',
    era: 'Pioneers',
    eraGroup: 'pioneers',
    year: 1968,
    topology: 'fet',
    description: 'Eddie Kramer 1176-style FET limiting. Controls extreme dynamics of feedback and wah while preserving explosive transients.',
    confidence: 'A',
    referenceAlbums: ['Electric Ladyland', 'Are You Experienced'],
    params: { threshold: -14, ratio: 8, attack: 0.8, release: 180, knee: 3, makeupGain: 6, autoMakeup: false },
  },

  // ============================================================
  // 1970s: THE GOLDEN ERA
  // ============================================================
  {
    id: 'jimmy_page',
    name: 'Jimmy Page',
    era: '1970s',
    eraGroup: '1970s',
    year: 1971,
    topology: 'fet',
    description: 'Glyn/Andy Johns at Headley Grange. 1176s on Les Paul through cranked Marshalls. Medium attack preserves pick, fast release for sustain.',
    confidence: 'A',
    referenceAlbums: ['Led Zeppelin IV', 'Physical Graffiti'],
    params: { threshold: -16, ratio: 4, attack: 3, release: 120, knee: 4, makeupGain: 5, autoMakeup: false },
  },
  {
    id: 'carlos_santana',
    name: 'Carlos Santana',
    era: '1970s',
    eraGroup: '1970s',
    year: 1970,
    topology: 'opto',
    description: 'Opto for smooth vocal-like sustain. Long held notes bloom with program-dependent release. Vari-mu bus warmth.',
    confidence: 'B',
    referenceAlbums: ['Abraxas', 'Amigos'],
    params: { threshold: -22, ratio: 3, attack: 15, release: 800, knee: 12, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'david_gilmour',
    name: 'David Gilmour',
    era: '1970s',
    eraGroup: '1970s',
    year: 1973,
    topology: 'opto',
    description: 'Abbey Road with Alan Parsons. Singing sustain — compression extends note decay without squashing initial pick attack.',
    confidence: 'A',
    referenceAlbums: ['The Dark Side of the Moon', 'The Wall'],
    params: { threshold: -24, ratio: 2.5, attack: 25, release: 1200, knee: 14, makeupGain: 5, autoMakeup: false },
  },
  {
    id: 'tony_iommi',
    name: 'Tony Iommi',
    era: '1970s',
    eraGroup: '1970s',
    year: 1971,
    topology: 'fet',
    description: 'Aggressive FET limiting to tighten low-end sludge. Fast attack, fast release, high ratio — controlling chaos.',
    confidence: 'B',
    referenceAlbums: ['Master of Reality', 'Vol. 4'],
    params: { threshold: -12, ratio: 12, attack: 0.5, release: 100, knee: 2, makeupGain: 8, autoMakeup: false },
  },
  {
    id: 'peter_green',
    name: 'Peter Green',
    era: '1970s',
    eraGroup: '1970s',
    year: 1969,
    topology: 'opto',
    description: 'Blue Horizon Studios. Out-of-phase Les Paul tone — opto enhances singing midrange and tames brightness.',
    confidence: 'B',
    referenceAlbums: ['Then Play On', 'Albatross'],
    params: { threshold: -26, ratio: 2, attack: 30, release: 600, knee: 16, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'brian_may',
    name: 'Brian May',
    era: '1970s',
    eraGroup: '1970s',
    year: 1975,
    topology: 'fet',
    description: 'Roy Thomas Baker at Trident. Each guitar track FET-compressed for density, harmony bus VCA-compressed for alignment.',
    confidence: 'A',
    referenceAlbums: ['A Night at the Opera', 'News of the World'],
    params: { threshold: -14, ratio: 6, attack: 2, release: 150, knee: 4, makeupGain: 6, autoMakeup: false },
  },
  {
    id: 'mark_knopfler',
    name: 'Mark Knopfler',
    era: '1970s',
    eraGroup: '1970s',
    year: 1978,
    topology: 'opto',
    description: 'Transparent compression preserving fingerpicked dynamics. Very gentle ratio, slow attack preserves snap.',
    confidence: 'B',
    referenceAlbums: ['Dire Straits', "Communiqué"],
    params: { threshold: -28, ratio: 2, attack: 35, release: 500, knee: 18, makeupGain: 2, autoMakeup: false },
  },
  {
    id: 'lindsey_buckingham',
    name: 'Lindsey Buckingham',
    era: '1970s',
    eraGroup: '1970s',
    year: 1977,
    topology: 'vca',
    description: 'Ken Caillat at Village Recorder. dbx 160 for clean, precise dynamics on aggressive fingerpicked acoustic and layered electric.',
    confidence: 'A',
    referenceAlbums: ['Rumours', 'Tusk'],
    params: { threshold: -18, ratio: 3, attack: 8, release: 200, knee: 6, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'acdc',
    name: 'Angus & Malcolm Young',
    era: '1970s',
    eraGroup: '1970s',
    year: 1979,
    topology: 'fet',
    description: '1176 on both guitar tracks. Malcolm moderate compression as bedrock, Angus slightly less for dynamic expression.',
    confidence: 'A',
    referenceAlbums: ['Highway to Hell', 'Back in Black'],
    params: { threshold: -15, ratio: 4, attack: 3, release: 130, knee: 3, makeupGain: 5, autoMakeup: false },
  },
  {
    id: 'jerry_garcia',
    name: 'Jerry Garcia',
    era: '1970s',
    eraGroup: '1970s',
    year: 1972,
    topology: 'opto',
    description: 'Wally Heider Studios. Handles extreme dynamic range without audible pumping. Very slow, transparent.',
    confidence: 'B',
    referenceAlbums: ["Europe '72", 'American Beauty'],
    params: { threshold: -26, ratio: 2, attack: 30, release: 1000, knee: 18, makeupGain: 3, autoMakeup: false },
  },

  // ============================================================
  // 1980s: HIGH-GAIN AND PRECISION
  // ============================================================
  {
    id: 'eddie_van_halen',
    name: 'Eddie Van Halen',
    era: '1980s',
    eraGroup: '1980s',
    year: 1978,
    topology: 'fet',
    description: 'Ted Templeman at Sunset Sound. Brown sound — FET manages extreme sustain and harmonic overtones of tapping.',
    confidence: 'A',
    referenceAlbums: ['Van Halen', 'Van Halen II'],
    params: { threshold: -14, ratio: 8, attack: 1, release: 200, knee: 3, makeupGain: 7, autoMakeup: false },
  },
  {
    id: 'randy_rhoads',
    name: 'Randy Rhoads',
    era: '1980s',
    eraGroup: '1980s',
    year: 1981,
    topology: 'fet',
    description: 'Max Norman at Ridge Farm. FET compression for sustain and density on Marshall/MXR tone.',
    confidence: 'B',
    referenceAlbums: ['Blizzard of Ozz', 'Diary of a Madman'],
    params: { threshold: -15, ratio: 6, attack: 2, release: 160, knee: 4, makeupGain: 6, autoMakeup: false },
  },
  {
    id: 'the_edge',
    name: 'The Edge',
    era: '1980s',
    eraGroup: '1980s',
    year: 1984,
    topology: 'opto',
    description: 'Eno/Lanois. FET manages pick attack above delay repeats. Opto bus smooths cascading echoes into cohesive wash.',
    confidence: 'B',
    referenceAlbums: ['The Unforgettable Fire', 'The Joshua Tree'],
    params: { threshold: -22, ratio: 3, attack: 12, release: 800, knee: 10, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'slash',
    name: 'Slash',
    era: '1980s',
    eraGroup: '1980s',
    year: 1987,
    topology: 'fet',
    description: 'Mike Clink at Rumbo. 1176 adds sustain and midrange thickness. Medium attack lets initial transient bite.',
    confidence: 'A',
    referenceAlbums: ['Appetite for Destruction'],
    params: { threshold: -14, ratio: 4, attack: 5, release: 140, knee: 3, makeupGain: 5, autoMakeup: false },
  },
  {
    id: 'james_hetfield',
    name: 'James Hetfield',
    era: '1980s',
    eraGroup: '1980s',
    year: 1986,
    topology: 'vca',
    description: 'Sweet Silence Studios. Surgical VCA — palm-muted downpicking needs absolute consistency. Precision over character.',
    confidence: 'A',
    referenceAlbums: ['Master of Puppets', 'Ride the Lightning'],
    params: { threshold: -12, ratio: 6, attack: 1, release: 80, knee: 2, makeupGain: 6, autoMakeup: false },
  },
  {
    id: 'robert_smith',
    name: 'Robert Smith',
    era: '1980s',
    eraGroup: '1980s',
    year: 1989,
    topology: 'opto',
    description: 'Hook End Manor. Opto for clean shimmering passages. FET for denser distorted sections. No level jumps in transition.',
    confidence: 'B',
    referenceAlbums: ['Disintegration', 'Kiss Me, Kiss Me, Kiss Me'],
    params: { threshold: -24, ratio: 2.5, attack: 20, release: 700, knee: 12, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'johnny_marr',
    name: 'Johnny Marr',
    era: '1980s',
    eraGroup: '1980s',
    year: 1986,
    topology: 'opto',
    description: 'Opto for jangly clean Rickenbacker. VCA bus for transparent level control across multiple arpeggiated overdubs.',
    confidence: 'B',
    referenceAlbums: ['The Queen Is Dead', 'Strangeways, Here We Come'],
    params: { threshold: -24, ratio: 2, attack: 25, release: 500, knee: 14, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'alex_lifeson',
    name: 'Alex Lifeson',
    era: '1980s',
    eraGroup: '1980s',
    year: 1981,
    topology: 'fet',
    description: 'Terry Brown at Le Studio. FET on distorted rhythm tracks, VCA on clean arpeggiated sections. Wide tonal range.',
    confidence: 'B',
    referenceAlbums: ['Moving Pictures', 'Signals'],
    params: { threshold: -16, ratio: 4, attack: 3, release: 180, knee: 6, makeupGain: 5, autoMakeup: false },
  },
  {
    id: 'andy_summers',
    name: 'Andy Summers',
    era: '1980s',
    eraGroup: '1980s',
    year: 1983,
    topology: 'opto',
    description: 'Hugh Padgham at AIR Studios. Opto for spatial tones. Slow attack preserves chorus sweep.',
    confidence: 'B',
    referenceAlbums: ['Synchronicity', 'Ghost in the Machine'],
    params: { threshold: -22, ratio: 2.5, attack: 25, release: 600, knee: 12, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'srv',
    name: 'Stevie Ray Vaughan',
    era: '1980s',
    eraGroup: '1980s',
    year: 1983,
    topology: 'fet',
    description: 'FET manages immense dynamic range — whisper-clean to screaming leads. Moderate compression, raw feel preserved.',
    confidence: 'A',
    referenceAlbums: ['Texas Flood', "Couldn't Stand the Weather"],
    params: { threshold: -18, ratio: 4, attack: 5, release: 200, knee: 6, makeupGain: 4, autoMakeup: false },
  },

  // ============================================================
  // 1990s: ALTERNATIVE AND EXTREME DYNAMICS
  // ============================================================
  {
    id: 'kurt_cobain',
    name: 'Kurt Cobain',
    era: '1990s',
    eraGroup: '1990s',
    year: 1991,
    topology: 'fet',
    description: 'Butch Vig at Sound City. Chorus guitar slammed through 1176 for wall-of-sound density. Extreme quiet-loud dynamic.',
    confidence: 'A',
    referenceAlbums: ['Nevermind', 'In Utero'],
    params: { threshold: -10, ratio: 12, attack: 0.5, release: 100, knee: 2, makeupGain: 8, autoMakeup: false },
  },
  {
    id: 'tom_morello',
    name: 'Tom Morello',
    era: '1990s',
    eraGroup: '1990s',
    year: 1992,
    topology: 'fet',
    description: '1176 all-buttons mode. Kill-switch stutters, whammy dives, toggle scratching produce extreme transients. Aggressive taming.',
    confidence: 'A',
    referenceAlbums: ['Rage Against the Machine', 'Evil Empire'],
    params: { threshold: -8, ratio: 20, attack: 0.2, release: 60, knee: 0, makeupGain: 10, autoMakeup: false },
  },
  {
    id: 'billy_corgan',
    name: 'Billy Corgan',
    era: '1990s',
    eraGroup: '1990s',
    year: 1993,
    topology: 'limiter',
    description: 'Butch Vig/Flood. Hundreds of overdubbed layers through Big Muff. Each FET-compressed, guitar bus limited for unified wall.',
    confidence: 'A',
    referenceAlbums: ['Siamese Dream', 'Mellon Collie'],
    params: { threshold: -6, ratio: 20, attack: 0.3, release: 80, knee: 1, makeupGain: 10, autoMakeup: false },
  },
  {
    id: 'kim_thayil',
    name: 'Kim Thayil',
    era: '1990s',
    eraGroup: '1990s',
    year: 1994,
    topology: 'fet',
    description: 'Detuned Guild S-100. FET with sidechain HPF to prevent low strings dominating gain reduction. Fast attack, aggressive ratio.',
    confidence: 'B',
    referenceAlbums: ['Superunknown', 'Badmotorfinger'],
    params: { threshold: -12, ratio: 8, attack: 1, release: 120, knee: 2, makeupGain: 7, autoMakeup: false },
  },
  {
    id: 'jonny_greenwood',
    name: 'Jonny Greenwood',
    era: '1990s',
    eraGroup: '1990s',
    year: 1997,
    topology: 'varimu',
    description: 'Nigel Godrich. Vari-mu bus for atmospheric quiet passages. FET for aggressive distorted intrusions. Extreme dynamic range.',
    confidence: 'B',
    referenceAlbums: ['OK Computer', 'The Bends'],
    params: { threshold: -22, ratio: 2, attack: 15, release: 1000, knee: 14, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'john_frusciante',
    name: 'John Frusciante',
    era: '1990s',
    eraGroup: '1990s',
    year: 1999,
    topology: 'opto',
    description: 'Rick Rubin at Cello Studios. Opto for smooth funk rhythms. Slow attack critical — must not squash ghost notes.',
    confidence: 'B',
    referenceAlbums: ['Californication', 'By the Way'],
    params: { threshold: -22, ratio: 3, attack: 20, release: 500, knee: 10, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'mike_einziger',
    name: 'Mike Einziger',
    era: '1990s',
    eraGroup: '1990s',
    year: 1999,
    topology: 'vca',
    description: 'Scott Litt at NRG. VCA precision on clean passages, FET aggression on driven sections. Adapts to stylistic shifts.',
    confidence: 'C',
    referenceAlbums: ['Make Yourself', 'Morning View'],
    params: { threshold: -18, ratio: 3, attack: 8, release: 200, knee: 8, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'stephen_carpenter',
    name: 'Stephen Carpenter',
    era: '1990s',
    eraGroup: '1990s',
    year: 2000,
    topology: 'limiter',
    description: 'Terry Date. 8-string baritone tunings — FET with aggressive sidechain HPF. Limiter prevents detuned power chords overwhelming mix.',
    confidence: 'B',
    referenceAlbums: ['White Pony', 'Around the Fur'],
    params: { threshold: -8, ratio: 20, attack: 0.3, release: 80, knee: 1, makeupGain: 8, autoMakeup: false },
  },
  {
    id: 'josh_homme',
    name: 'Josh Homme',
    era: '1990s',
    eraGroup: '1990s',
    year: 2002,
    topology: 'fet',
    description: 'Sound City. "Robot rock" — cranked amps already extremely compressed. FET adds further sustain and tightens rhythm.',
    confidence: 'B',
    referenceAlbums: ['Songs for the Deaf', 'Rated R'],
    params: { threshold: -16, ratio: 4, attack: 3, release: 150, knee: 4, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'jack_white',
    name: 'Jack White',
    era: '1990s',
    eraGroup: '1990s',
    year: 2003,
    topology: 'fet',
    description: 'Lo-fi 1176 pushed hard for saturation. No bass guitar — guitar compression fills entire low-mid and mid spectrum.',
    confidence: 'B',
    referenceAlbums: ['Elephant', 'White Blood Cells'],
    params: { threshold: -10, ratio: 12, attack: 1, release: 100, knee: 2, makeupGain: 9, autoMakeup: false },
  },

  // ============================================================
  // 2000s-2010s: MODERN CRAFT
  // ============================================================
  {
    id: 'john_mayer',
    name: 'John Mayer',
    era: '2000s',
    eraGroup: '2000s',
    year: 2003,
    topology: 'opto',
    description: 'Jack Joseph Puig at Ocean Way. Smoothest possible dynamics — very gentle ratio, slow attack. Compression must be invisible.',
    confidence: 'B',
    referenceAlbums: ['Room for Squares', 'Continuum'],
    params: { threshold: -28, ratio: 2, attack: 30, release: 600, knee: 18, makeupGain: 2, autoMakeup: true },
  },
  {
    id: 'dan_auerbach',
    name: 'Dan Auerbach',
    era: '2000s',
    eraGroup: '2000s',
    year: 2010,
    topology: 'fet',
    description: 'Easy Eye Sound. Raw garage-blues. FET pushed for harmonic character — 1176 saturation is part of the tone.',
    confidence: 'B',
    referenceAlbums: ['Brothers', 'El Camino'],
    params: { threshold: -12, ratio: 8, attack: 1, release: 120, knee: 2, makeupGain: 7, autoMakeup: false },
  },
  {
    id: 'annie_clark',
    name: 'Annie Clark',
    era: '2000s',
    eraGroup: '2000s',
    year: 2014,
    topology: 'fet',
    description: 'John Congleton. Sharp angular tone — FET fast attack clips transient for punchy, almost keyboard-like quality.',
    confidence: 'B',
    referenceAlbums: ['St. Vincent', 'Masseduction'],
    params: { threshold: -14, ratio: 6, attack: 0.5, release: 100, knee: 2, makeupGain: 6, autoMakeup: false },
  },
  {
    id: 'omar_rodriguez_lopez',
    name: "Omar Rodríguez-López",
    era: '2000s',
    eraGroup: '2000s',
    year: 2003,
    topology: 'limiter',
    description: 'Rick Rubin at Sound City. Chaotic high-gain improvisations. FET manages feedback and oscillation into limiting for extreme moments.',
    confidence: 'B',
    referenceAlbums: ['Deloused in the Comatorium', 'Frances the Mute'],
    params: { threshold: -8, ratio: 20, attack: 0.3, release: 80, knee: 1, makeupGain: 9, autoMakeup: false },
  },
  {
    id: 'tosin_abasi',
    name: 'Tosin Abasi',
    era: '2000s',
    eraGroup: '2000s',
    year: 2014,
    topology: 'vca',
    description: 'Surgical VCA — 8-string extended range demands precision dynamics. Clean colorless compression preserving tapping clarity.',
    confidence: 'B',
    referenceAlbums: ['The Joy of Motion', 'The Madness of Many'],
    params: { threshold: -16, ratio: 3, attack: 2, release: 120, knee: 4, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'nile_rodgers',
    name: 'Nile Rodgers',
    era: '2000s',
    eraGroup: '2000s',
    year: 1977,
    topology: 'vca',
    description: 'Bob Clearmountain at Power Station. VCA for tight consistent rhythm — every 16th-note strum identical level. Mechanical groove.',
    confidence: 'A',
    referenceAlbums: ['Le Freak', 'Good Times', "Let's Dance"],
    params: { threshold: -14, ratio: 4, attack: 5, release: 100, knee: 4, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'derek_trucks',
    name: 'Derek Trucks',
    era: '2000s',
    eraGroup: '2000s',
    year: 2009,
    topology: 'opto',
    description: 'Opto handles extreme sustain and continuous pitch movement of slide playing. Slow attack preserves slide gesture.',
    confidence: 'B',
    referenceAlbums: ['Already Free', 'Revelator'],
    params: { threshold: -24, ratio: 2.5, attack: 25, release: 800, knee: 14, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'yvette_young',
    name: 'Yvette Young',
    era: '2000s',
    eraGroup: '2000s',
    year: 2018,
    topology: 'opto',
    description: 'Math-rock tapping and harmonics. Opto for melodic clean passages. Slow attack preserves tap transient articulation.',
    confidence: 'C',
    referenceAlbums: ['Effloresce', 'Technicolor'],
    params: { threshold: -24, ratio: 2, attack: 25, release: 500, knee: 14, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'mateus_asato',
    name: 'Mateus Asato',
    era: '2000s',
    eraGroup: '2000s',
    year: 2019,
    topology: 'opto',
    description: 'Clean-amp expressive dynamics. Very gentle ratio — nearly indistinguishable from bypass at moderate levels, engaging only on peaks.',
    confidence: 'C',
    referenceAlbums: ['The Creation'],
    params: { threshold: -30, ratio: 1.5, attack: 35, release: 500, knee: 20, makeupGain: 1, autoMakeup: true },
  },
  {
    id: 'tim_henson',
    name: 'Tim Henson',
    era: '2000s',
    eraGroup: '2000s',
    year: 2022,
    topology: 'vca',
    description: 'Hyper-clean synth-like tone. Surgical VCA — complex tapping, slapping, harmonic techniques demand absolute clarity.',
    confidence: 'B',
    referenceAlbums: ['Remember That You Will Die', 'New Levels New Devils'],
    params: { threshold: -16, ratio: 3, attack: 2, release: 100, knee: 4, makeupGain: 4, autoMakeup: false },
  },
  {
    id: 'sarah_longfield',
    name: 'Sarah Longfield',
    era: '2000s',
    eraGroup: '2000s',
    year: 2020,
    topology: 'vca',
    description: '8-string extended range. Clean precise compression — tapping and progressive techniques need transparency above all.',
    confidence: 'C',
    referenceAlbums: ['Disparity', 'Collapse'],
    params: { threshold: -18, ratio: 3, attack: 3, release: 150, knee: 6, makeupGain: 3, autoMakeup: false },
  },
  {
    id: 'mark_lettieri',
    name: 'Mark Lettieri',
    era: '2000s',
    eraGroup: '2000s',
    year: 2020,
    topology: 'vca',
    description: 'VCA precision on tight funk rhythm parts, opto warmth on jazz-inflected solos. Handles abrupt style shifts.',
    confidence: 'B',
    referenceAlbums: ['We Like It Here', 'Spark and Echo'],
    params: { threshold: -16, ratio: 3, attack: 5, release: 150, knee: 6, makeupGain: 3, autoMakeup: false },
  },
]

export function getPresetsByEra(eraGroup: string): CelestialPreset[] {
  return CELESTIAL_PRESETS.filter(p => p.eraGroup === eraGroup)
}

export function getPresetById(id: string): CelestialPreset | undefined {
  return CELESTIAL_PRESETS.find(p => p.id === id)
}
