"""Canonical Pydantic schemas for the device-peak-meters WebSocket frame
envelope.

Established by the run-13i handoff (2026-05-14) as next-session order-1
pick: "OpenAPI generation for the shared WS frame envelope — every WS
endpoint in `device_meters.py` emits a `device_peak_meters:*` versioned
frame. A single dataclass + schema export would let backend tests
assert the frame shape against a single source of truth."

Two endpoints emit four frame variants on two topics:

  topic `device_peak_meters:registry` (from /api/v1/devices/peak-meters/stream)
    - DeviceMeterRegistryFrame   — full snapshot
    - DeviceMeterRegistryError   — defensive error envelope (currently no-op;
                                    the local stream returns no errors path,
                                    but the schema is symmetric for parity)

  topic `device_peak_meters:cluster_registry` (from /api/v1/devices/peak-meters/cluster/stream)
    - ClusterMeterRegistryFrame  — local + peers + errors aggregate
    - ClusterMeterRegistryError  — single-error fallback when fan-out fails

The route handlers in app/routes/device_meters.py construct their
frames from these models via .model_dump(). Tests assert the frame
shape via `model_validate(frame)`. The OpenAPI surface is generated by
FastAPI from the same models on a GET handler that exists purely to
publish the schema (the WS endpoints don't generate OpenAPI directly).

Schema versioning: `schema_version` is bumped only on breaking changes
to the `data` payload. Adding a new optional field keeps `schema_version=1`;
removing a field or changing its type bumps to 2 and the route's
emission code updates accordingly.
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Per-snapshot models (shared between local + cluster frames)
# ---------------------------------------------------------------------------


class MeterSnapshotPayload(BaseModel):
    """Per-channel peak-dBFS snapshot for a single device.

    Mirrors the dataclass `app.services.devices._meter_source.MeterSnapshot`
    but as a serializable Pydantic model (the WS payload is JSON).
    """

    input_peak_db: list[float] = Field(
        default_factory=list,
        description="Peak dBFS per input channel; -100.0 means silence.",
    )
    output_peak_db: list[float] = Field(
        default_factory=list,
        description="Peak dBFS per output channel.",
    )
    source: Literal["engine", "placeholder"] = Field(
        default="placeholder",
        description=(
            "`engine` = measured from the live engine ring buffer; "
            "`placeholder` = silence fallback (no measurement yet)."
        ),
    )
    captured_at: Optional[float] = Field(
        default=None,
        description=(
            "Unix timestamp (seconds since epoch) when the source "
            "produced the snapshot. None means the source did not stamp it; "
            "the registry backfills with the current wall-clock so consumers "
            "can always render 'n seconds ago'."
        ),
    )


class DeviceMeterRow(BaseModel):
    """One device's slot in a registry frame's `data.devices[]` array."""

    device_id: str = Field(..., description="Stable device identifier (kebab-case).")
    input_channels: int = Field(..., ge=0, description="Channel count for inputs.")
    output_channels: int = Field(..., ge=0, description="Channel count for outputs.")
    has_engine_source: bool = Field(
        ...,
        description=(
            "True iff the registry has an engine-backed source registered "
            "(vs the silence placeholder). UI can label devices that haven't "
            "yet received an engine tap."
        ),
    )
    snapshot: MeterSnapshotPayload = Field(
        default_factory=MeterSnapshotPayload,
        description="Latest per-channel peak measurement.",
    )


# ---------------------------------------------------------------------------
# Local registry frame
# ---------------------------------------------------------------------------


class DeviceMeterRegistryData(BaseModel):
    """The `data` field of a `device_peak_meters:registry` frame."""

    devices: list[DeviceMeterRow] = Field(
        default_factory=list,
        description="Alphabetical by device_id over the filter set.",
    )


class DeviceMeterRegistryFrame(BaseModel):
    """Frame envelope emitted by `/api/v1/devices/peak-meters/stream`."""

    type: Literal["device_peak_meters:registry"] = "device_peak_meters:registry"
    schema_version: Literal[1] = 1
    data: DeviceMeterRegistryData


# ---------------------------------------------------------------------------
# Cluster registry frame (local + peers + errors)
# ---------------------------------------------------------------------------


class ClusterPeerSlice(BaseModel):
    """One peer's contribution to a cluster registry frame."""

    node_id: str = Field(..., description="Discovered peer node ID.")
    hostname: Optional[str] = Field(
        default=None,
        description="Display hostname; None when discovery hasn't resolved it yet.",
    )
    devices: list[DeviceMeterRow] = Field(default_factory=list)
    fetch_age_seconds: Optional[float] = Field(
        default=None,
        description=(
            "How long ago the fan-out fetch completed for this peer "
            "(seconds). Used by the cluster overview's per-row 'last seen' "
            "Tag."
        ),
    )


class ClusterMeterRegistryData(BaseModel):
    """The `data` field of a `device_peak_meters:cluster_registry` frame."""

    local: DeviceMeterRegistryData = Field(
        default_factory=DeviceMeterRegistryData,
        description="The local node's slice (empty when filtered out).",
    )
    peers: list[ClusterPeerSlice] = Field(
        default_factory=list,
        description="Per-peer slices over the filter set.",
    )
    errors: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Per-node error string keyed by node_id; `@local` reserved for "
            "the local node's own snapshot failure path."
        ),
    )


class ClusterMeterRegistryFrame(BaseModel):
    """Frame envelope emitted by `/api/v1/devices/peak-meters/cluster/stream`."""

    type: Literal["device_peak_meters:cluster_registry"] = (
        "device_peak_meters:cluster_registry"
    )
    schema_version: Literal[1] = 1
    data: ClusterMeterRegistryData


# ---------------------------------------------------------------------------
# Convenience helpers — used by route handlers to build/validate frames
# without duplicating the literal type+version pairing across files.
# ---------------------------------------------------------------------------


def build_registry_frame(rows: list[DeviceMeterRow]) -> dict:
    """Materialize a local-stream frame from a list of rows. Route handler
    convenience that keeps the literal `type` + `schema_version` pair in
    exactly one place."""
    return DeviceMeterRegistryFrame(
        data=DeviceMeterRegistryData(devices=rows),
    ).model_dump()


def build_cluster_registry_frame(
    *,
    local: DeviceMeterRegistryData | None = None,
    peers: list[ClusterPeerSlice] | None = None,
    errors: dict[str, str] | None = None,
) -> dict:
    """Materialize a cluster-stream frame. Same single-source-of-truth
    intent as `build_registry_frame`."""
    return ClusterMeterRegistryFrame(
        data=ClusterMeterRegistryData(
            local=local or DeviceMeterRegistryData(),
            peers=peers or [],
            errors=errors or {},
        ),
    ).model_dump()


def validate_registry_frame(frame: dict) -> DeviceMeterRegistryFrame:
    """Tests use this to assert the frame shape against the canonical model."""
    return DeviceMeterRegistryFrame.model_validate(frame)


def validate_cluster_registry_frame(frame: dict) -> ClusterMeterRegistryFrame:
    return ClusterMeterRegistryFrame.model_validate(frame)


__all__ = [
    "MeterSnapshotPayload",
    "DeviceMeterRow",
    "DeviceMeterRegistryData",
    "DeviceMeterRegistryFrame",
    "ClusterPeerSlice",
    "ClusterMeterRegistryData",
    "ClusterMeterRegistryFrame",
    "build_registry_frame",
    "build_cluster_registry_frame",
    "validate_registry_frame",
    "validate_cluster_registry_frame",
]
