"""
Zero-Touch Provisioning (ZTP) System for MAP2 Audio Cluster

Handles automatic node configuration on first boot:
- First-boot detection
- Node ID generation
- Hardware capability detection
- Deployment mode assignment
- SSH key provisioning
- Initial cluster registration
"""

import asyncio
import logging
import os
import socket
from pathlib import Path
from typing import Optional
from datetime import datetime

from app.services.cluster.enhanced_node_identity import (
    get_enhanced_node_identity,
    EnhancedNodeIdentity,
)

logger = logging.getLogger(__name__)


class ZTPBootstrap:
    """
    Zero-Touch Provisioning bootstrap service.

    Runs automatically on first boot to configure new cluster nodes
    without manual intervention.
    """

    def __init__(self):
        """Initialize ZTP bootstrap"""
        self.node_identity: Optional[EnhancedNodeIdentity] = None
        self.config_file = Path("/etc/map2/node.conf")
        self.marker_file = Path("/var/lib/map2/.ztp-complete")
        self.logger = logging.getLogger(__name__)

    def is_first_boot(self) -> bool:
        """
        Detect if this is first boot.

        Returns:
            True if first boot, False if already configured
        """
        # Check marker file (most reliable)
        if self.marker_file.exists():
            self.logger.info("ZTP: Already completed (marker exists)")
            return False

        # Check if node config exists
        if self.config_file.exists():
            self.logger.info("ZTP: Already completed (config exists)")
            return False

        self.logger.info("ZTP: First boot detected")
        return True

    async def run_ztp(self) -> bool:
        """
        Execute full ZTP workflow.

        Returns:
            True if successful, False otherwise
        """
        try:
            if not self.is_first_boot():
                self.logger.debug("ZTP: Skipping (not first boot)")
                return True

            self.logger.info("ZTP: Starting first-boot provisioning...")

            # Step 1: Generate/load node identity
            if not await self._setup_node_identity():
                self.logger.error("ZTP: Failed to setup node identity")
                return False

            # Step 2: Provision SSH keys
            if not await self._provision_ssh_keys():
                self.logger.error("ZTP: Failed to provision SSH keys")
                return False

            # Step 3: Create system directories
            if not await self._create_directories():
                self.logger.error("ZTP: Failed to create directories")
                return False

            # Step 4: Write ZTP completion marker
            if not await self._create_completion_marker():
                self.logger.error("ZTP: Failed to create completion marker")
                return False

            # Step 5: Log completion
            self.logger.info(
                f"ZTP: Provisioning complete for {self.node_identity.get_node_id()}"
            )

            return True

        except Exception as e:
            self.logger.error(f"ZTP: Fatal error: {e}", exc_info=True)
            return False

    async def _setup_node_identity(self) -> bool:
        """
        Setup node identity with hardware detection.

        Returns:
            True if successful
        """
        try:
            self.logger.info("ZTP: Setting up node identity...")

            # Get or create enhanced node identity
            self.node_identity = get_enhanced_node_identity()

            node_id = self.node_identity.get_node_id()
            role = self.node_identity.get_role()
            caps = self.node_identity.get_capabilities()

            self.logger.info(f"ZTP: Node ID: {node_id}")
            self.logger.info(f"ZTP: Role: {role}")
            self.logger.info(f"ZTP: CPU: {caps.cpu_cores} cores ({caps.cpu_model})")
            self.logger.info(f"ZTP: Memory: {caps.total_memory_gb} GB")
            self.logger.info(f"ZTP: Audio: {caps.has_audio_interface}")
            self.logger.info(f"ZTP: Storage: {caps.storage_gb} GB")
            self.logger.info(f"ZTP: Kernel: {caps.kernel_version}")

            return True

        except Exception as e:
            self.logger.error(f"ZTP: Node identity setup failed: {e}", exc_info=True)
            return False

    async def _provision_ssh_keys(self) -> bool:
        """
        Provision SSH keys for node-to-node communication.

        Returns:
            True if successful
        """
        try:
            self.logger.info("ZTP: Provisioning SSH keys...")

            ssh_dir = Path("/etc/map2/ssh")
            ssh_dir.mkdir(parents=True, exist_ok=True)

            # SSH keys are already generated by enhanced_node_identity
            # Verify they exist
            node_id = self.node_identity.get_node_id()
            key_path = Path.home() / ".ssh" / f"map2_{node_id}"

            if key_path.exists() and Path(f"{key_path}.pub").exists():
                self.logger.info(
                    f"ZTP: SSH keys verified for {node_id}"
                )
                return True
            else:
                self.logger.warning(
                    f"ZTP: SSH keys not found for {node_id}, will be created on next startup"
                )
                return True

        except Exception as e:
            self.logger.error(f"ZTP: SSH provisioning failed: {e}", exc_info=True)
            return False

    async def _create_directories(self) -> bool:
        """
        Create required system directories.

        Returns:
            True if successful
        """
        try:
            self.logger.info("ZTP: Creating system directories...")

            directories = [
                "/etc/map2",
                "/etc/map2/ssl",
                "/etc/map2/ssh",
                "/var/lib/map2",
                "/var/lib/map2/backups",
                "/var/lib/map2/config-repo",
                "/opt/map2/scripts",
                "/opt/map2/dashboards",
            ]

            for dir_path in directories:
                path = Path(dir_path)
                path.mkdir(parents=True, exist_ok=True)
                self.logger.debug(f"ZTP: Created/verified {dir_path}")

            # Set permissions
            Path("/etc/map2").chmod(0o755)
            Path("/var/lib/map2").chmod(0o755)
            Path("/etc/map2/ssl").chmod(0o700)
            Path("/etc/map2/ssh").chmod(0o700)

            self.logger.info("ZTP: All directories created")
            return True

        except Exception as e:
            self.logger.error(f"ZTP: Directory creation failed: {e}", exc_info=True)
            return False

    async def _create_completion_marker(self) -> bool:
        """
        Create marker file to indicate ZTP completion.

        Returns:
            True if successful
        """
        try:
            self.logger.info("ZTP: Creating completion marker...")

            marker_dir = self.marker_file.parent
            marker_dir.mkdir(parents=True, exist_ok=True)

            # Write marker with timestamp
            with open(self.marker_file, "w") as f:
                f.write(f"ZTP completed: {datetime.utcnow().isoformat()}\n")
                f.write(f"Node ID: {self.node_identity.get_node_id()}\n")
                f.write(f"Role: {self.node_identity.get_role()}\n")

            # Restrict permissions
            os.chmod(self.marker_file, 0o644)

            self.logger.info("ZTP: Completion marker created")
            return True

        except Exception as e:
            self.logger.error(
                f"ZTP: Completion marker creation failed: {e}", exc_info=True
            )
            return False

    async def register_with_cluster(self, management_node_ip: Optional[str] = None) -> bool:
        """
        Register this node with the management cluster.

        Args:
            management_node_ip: IP address of management node (optional)

        Returns:
            True if successful
        """
        try:
            if not self.node_identity:
                self.logger.error("ZTP: Node identity not initialized")
                return False

            self.logger.info("ZTP: Registering with cluster...")
            node_id = self.node_identity.get_node_id()
            node_cfg = getattr(self.node_identity, "config", None)
            node_name = node_cfg.hostname if node_cfg else socket.gethostname()
            node_ip = management_node_ip or self._resolve_primary_ip(node_name)
            role = self.node_identity.get_role()
            caps = self.node_identity.get_capabilities()
            
            # Import required services
            from app.services.cluster.registry import get_cluster_registry
            from app.services.cluster.certificate_authority import get_cluster_ca
            from app.services.cluster.mdns_discovery_enhanced import get_enhanced_mdns_discovery
            
            registry = get_cluster_registry()
            ca = get_cluster_ca()
            mdns = get_enhanced_mdns_discovery()
            
            if not registry or not ca:
                self.logger.warning("ZTP: Registry or CA not available, proceeding anyway")
            
            # 1. Register node in cluster registry
            if registry:
                try:
                    registry.add_or_update_node(
                        node_id=node_id,
                        hostname=node_name,
                        ip_address=node_ip,
                        role=role,
                        deployment_mode=role,
                        cpu_cores=caps.cpu_cores,
                        total_memory_gb=caps.total_memory_gb,
                        audio_devices=caps.audio_interfaces,
                        storage_gb=caps.storage_gb,
                        status="online",
                        metadata={"ztp_registered_at": datetime.utcnow().isoformat()},
                    )
                    self.logger.info(f"ZTP: Registered {node_id} in cluster registry")
                except Exception as e:
                    self.logger.error(f"ZTP: Failed to register in registry: {e}")
                    return False
            
            # 2. Request certificate from CA
            if ca:
                try:
                    if not ca.has_root_ca():
                        ca.generate_root_ca()

                    ca.issue_node_certificate(
                        node_id=node_id,
                        common_name=node_name,
                        sans=[node_name, node_ip],
                    )
                    self.logger.info(f"ZTP: Issued certificate for {node_id}")
                except Exception as e:
                    self.logger.error(f"ZTP: Failed to issue certificate: {e}")
                    # Don't fail registration - continue without cert for now
            
            # 3. Broadcast in mDNS discovery cache
            try:
                mdns.add_discovered_node(
                    node_id=node_id,
                    hostname=node_name,
                    addresses=[node_ip],
                    txt_records={
                        "cpu_cores": str(caps.cpu_cores),
                        "cpu_model": caps.cpu_model,
                        "memory_gb": str(caps.total_memory_gb),
                        "audio": ",".join(caps.audio_interfaces),
                        "storage_gb": str(caps.storage_gb),
                        "kernel": caps.kernel_version,
                        "gpu": "yes" if caps.has_gpuapu else "no",
                        "role": role,
                        "manager": "true" if role != "AUDIO-NODE" else "false",
                        "health": "100.0",
                    },
                    port=8000,
                )
                self.logger.info(f"ZTP: Added {node_id} to mDNS discovery cache")
            except Exception as e:
                self.logger.warning(f"ZTP: Failed to update mDNS cache: {e}")
            
            # 4. Add to Prometheus monitoring targets
            try:
                from app.services.cluster.prometheus_exporter import get_prometheus_exporter
                prom = get_prometheus_exporter()
                if prom:
                    prom.add_target(name=node_name, address=node_ip, port=9090)
                    self.logger.info(f"ZTP: Added {node_id} to Prometheus monitoring")
            except Exception as e:
                self.logger.warning(f"ZTP: Failed to add Prometheus monitoring: {e}")
            
            self.logger.info(f"ZTP: Node {node_id} successfully registered and provisioned")
            return True

        except Exception as e:
            self.logger.error(f"ZTP: Registration failed: {e}", exc_info=True)
            return False

    def _resolve_primary_ip(self, hostname: str) -> str:
        """Resolve a routable IP for this node, fallback to loopback."""
        try:
            addr = socket.gethostbyname(hostname)
            if addr and not addr.startswith("127."):
                return addr
        except Exception:
            pass

        try:
            test_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            test_sock.connect(("8.8.8.8", 80))
            return test_sock.getsockname()[0]
        except Exception:
            return "127.0.0.1"
        finally:
            try:
                test_sock.close()
            except Exception:
                pass


# Global ZTP instance
_ztp_instance: Optional[ZTPBootstrap] = None


def get_ztp_bootstrap() -> ZTPBootstrap:
    """Get or create the ZTP bootstrap singleton"""
    global _ztp_instance
    if _ztp_instance is None:
        _ztp_instance = ZTPBootstrap()
    return _ztp_instance


async def run_ztp_on_boot() -> bool:
    """
    Execute ZTP on boot (called from systemd service).

    Returns:
        True if successful or already configured
    """
    ztp = get_ztp_bootstrap()
    return await ztp.run_ztp()


# Main entry point for systemd service
if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    logger.info("MAP2 Zero-Touch Provisioning starting...")

    # Run ZTP
    result = asyncio.run(run_ztp_on_boot())

    if result:
        logger.info("ZTP: Provisioning successful")
        exit(0)
    else:
        logger.error("ZTP: Provisioning failed")
        exit(1)
