// AUTO-GENERATED — do not edit. Source: backend Pydantic models via
// scripts/generate_typescript_contracts.py (T2455).
// @ts-nocheck — this raw OpenAPI dump is consumed only through
//   `snapshots.contract.ts` (type-only re-exports for snapshot endpoints),
//   so type checking happens at the contract surface, not on the generated
//   schema implementation details.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** SnapshotChainInput */
        SnapshotChainInput: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Plugins */
            plugins?: components["schemas"]["SnapshotPluginInput"][];
            /** Loop Insertions */
            loop_insertions?: components["schemas"]["SnapshotLoopInsertionInput"][];
            /** Effects Loops */
            effects_loops?: {
                [key: string]: unknown;
            }[];
        };
        /** SnapshotChannelInput */
        SnapshotChannelInput: {
            /** Id */
            id?: number | null;
            /** Channel Key */
            channel_key?: string | null;
            /** Chain Id */
            chain_id?: number | null;
            /** Label */
            label?: string | null;
            /** Color */
            color?: string | null;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            /**
             * Solo
             * @default false
             */
            solo: boolean;
            /**
             * Dry Wet Mix
             * @default 100
             */
            dry_wet_mix: number;
        };
        /** SnapshotControlsInput */
        SnapshotControlsInput: {
            /** Midi Map */
            midi_map?: {
                [key: string]: unknown;
            }[];
            /** Automation Lanes */
            automation_lanes?: {
                [key: string]: unknown;
            }[];
            /** Expression Mappings */
            expression_mappings?: {
                [key: string]: unknown;
            }[];
            /** Monitoring Output Index */
            monitoring_output_index?: number | null;
            /** Input Interface Id */
            input_interface_id?: string | null;
            /** Output Interface Id */
            output_interface_id?: string | null;
            /** Maschine Encoder Map */
            maschine_encoder_map?: {
                [key: string]: unknown;
            };
        };
        /** SnapshotCreateRequest */
        SnapshotCreateRequest: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Tags */
            tags?: string[];
            /** Program Number */
            program_number?: number | null;
            /**
             * Tempo Bpm
             * @default 120
             */
            tempo_bpm: number;
            /** Derived From Snapshot Id */
            derived_from_snapshot_id?: number | null;
            /** Output Level Reference Dbfs */
            output_level_reference_dbfs?: number | null;
            /**
             * Output Level Warning Threshold Db
             * @default 3
             */
            output_level_warning_threshold_db: number | null;
            /** Input Device */
            input_device?: string | null;
            /** Output Device */
            output_device?: string | null;
            /**
             * Is Locked
             * @default false
             */
            is_locked: boolean;
            io_bindings?: components["schemas"]["SnapshotIOBindingsInput"] | null;
            controls?: components["schemas"]["SnapshotControlsInput"] | null;
            /** Paths */
            paths?: components["schemas"]["SnapshotPathInput"][] | null;
            /** Channels */
            channels?: components["schemas"]["SnapshotChannelInput"][];
            /** Chains */
            chains?: components["schemas"]["SnapshotChainInput"][];
            routing?: components["schemas"]["SnapshotRoutingInput"];
            /** Midi Map */
            midi_map?: {
                [key: string]: unknown;
            }[];
            /** Snapshot Data */
            snapshot_data?: {
                [key: string]: unknown;
            } | null;
        };
        /** SnapshotIOBindingsInput */
        SnapshotIOBindingsInput: {
            /** Input Device */
            input_device?: string | null;
            /** Output Device */
            output_device?: string | null;
            /** Input Interface Id */
            input_interface_id?: string | null;
            /** Output Interface Id */
            output_interface_id?: string | null;
            /** Monitoring Output Index */
            monitoring_output_index?: number | null;
        };
        /** SnapshotLoopInsertionInput */
        SnapshotLoopInsertionInput: {
            /** Insertion Id */
            insertion_id?: string | null;
            /** Loop Id */
            loop_id?: string | null;
            /**
             * Slot Index
             * @default 0
             */
            slot_index: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Mode
             * @default serial_insert
             */
            mode: string;
            /**
             * Blend Pct
             * @default 100
             */
            blend_pct: number;
            /**
             * Send Gain Db
             * @default 0
             */
            send_gain_db: number;
            /**
             * Return Gain Db
             * @default 0
             */
            return_gain_db: number;
            /**
             * Crossfade Ms
             * @default 12
             */
            crossfade_ms: number;
            /** Band Split Hz */
            band_split_hz?: number[];
        };
        /** SnapshotPathInput */
        SnapshotPathInput: {
            /** Id */
            id?: string | null;
            /** Name */
            name?: string | null;
            /** Label */
            label?: string | null;
            /** Color */
            color?: string | null;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            /**
             * Solo
             * @default false
             */
            solo: boolean;
            /**
             * Dry Wet Mix
             * @default 100
             */
            dry_wet_mix: number;
            /** Order Index */
            order_index?: number | null;
            /** Snapshot Chain Id */
            snapshot_chain_id?: number | null;
            /** Runtime Chain Id */
            runtime_chain_id?: number | null;
            /** Plugins */
            plugins?: components["schemas"]["SnapshotPluginInput"][];
            /** Loop Insertions */
            loop_insertions?: components["schemas"]["SnapshotLoopInsertionInput"][];
            /** Effects Loops */
            effects_loops?: {
                [key: string]: unknown;
            }[];
        };
        /** SnapshotPluginInput */
        SnapshotPluginInput: {
            /** Uri */
            uri: string;
            /** Name */
            name?: string | null;
            /** Position */
            position?: number | null;
            /**
             * Bypass
             * @default false
             */
            bypass: boolean;
            /** Parameters */
            parameters?: {
                [key: string]: number;
            };
            /** Loader State */
            loader_state?: {
                [key: string]: unknown;
            };
            /**
             * Is Placeholder
             * @default false
             */
            is_placeholder: boolean;
        };
        /** SnapshotRoutingInput */
        SnapshotRoutingInput: {
            /**
             * Mode
             * @default parallel_blend
             */
            mode: string;
            /** Active Channel Key */
            active_channel_key?: string | null;
            /** Blend Positions */
            blend_positions?: {
                [key: string]: number;
            };
            /**
             * Morph Position
             * @default 0.5
             */
            morph_position: number;
            /** Morph Source Channel Key */
            morph_source_channel_key?: string | null;
            /** Morph Target Channel Key */
            morph_target_channel_key?: string | null;
            /** Series Order */
            series_order?: string[];
        };
        /** SnapshotUpdateRequest */
        SnapshotUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Program Number */
            program_number?: number | null;
            /**
             * Create Revision
             * @default false
             */
            create_revision: boolean;
            /** Tempo Bpm */
            tempo_bpm?: number | null;
            /** Derived From Snapshot Id */
            derived_from_snapshot_id?: number | null;
            /** Output Level Reference Dbfs */
            output_level_reference_dbfs?: number | null;
            /** Output Level Warning Threshold Db */
            output_level_warning_threshold_db?: number | null;
            /** Input Device */
            input_device?: string | null;
            /** Output Device */
            output_device?: string | null;
            io_bindings?: components["schemas"]["SnapshotIOBindingsInput"] | null;
            controls?: components["schemas"]["SnapshotControlsInput"] | null;
            /** Paths */
            paths?: components["schemas"]["SnapshotPathInput"][] | null;
            /** Display Order */
            display_order?: number | null;
            /** Is Favorite */
            is_favorite?: boolean | null;
            /** Is Locked */
            is_locked?: boolean | null;
            /** Channels */
            channels?: components["schemas"]["SnapshotChannelInput"][] | null;
            /** Chains */
            chains?: components["schemas"]["SnapshotChainInput"][] | null;
            routing?: components["schemas"]["SnapshotRoutingInput"] | null;
            /** Midi Map */
            midi_map?: {
                [key: string]: unknown;
            }[] | null;
            /** Snapshot Data */
            snapshot_data?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
