#!/usr/bin/env python3
"""
Apply MAP2 clock-sync profiles for MPX1 S/PDIF and AVB.

This script is the canonical "one profile -> all rate mappings" tool.
It updates:
  1. ~/.map2/config.json (or caller-specified config path)
  2. PipeWire user profile fragment
  3. Optional systemd drop-in for map2-backend force-rate/force-quantum
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import pwd
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable

try:
    import yaml
except ImportError as exc:  # pragma: no cover - explicit operator-facing failure
    raise SystemExit(
        "PyYAML is required for scripts/apply_clock_sync_profile.py. "
        "Install with: pip install pyyaml"
    ) from exc


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROFILE_CATALOG = REPO_ROOT / "config" / "audio-clock-sync-profiles.yaml"
DEFAULT_SYSTEMD_DROPIN = Path(
    "/etc/systemd/system/map2-backend.service.d/20-clock-sync-profile.conf"
)


@dataclass(frozen=True)
class TargetPaths:
    config_file: Path
    pipewire_conf: Path
    systemd_dropin: Path | None


def _resolve_target_home(explicit_home: str | None) -> Path:
    if explicit_home:
        return Path(explicit_home).expanduser()

    if os.geteuid() == 0 and os.environ.get("SUDO_USER") and os.environ["SUDO_USER"] != "root":
        sudo_user = os.environ["SUDO_USER"]
        return Path(pwd.getpwnam(sudo_user).pw_dir)

    return Path.home()


def _resolve_paths(args: argparse.Namespace) -> TargetPaths:
    target_home = _resolve_target_home(args.target_home)
    config_file = Path(args.config_file).expanduser() if args.config_file else target_home / ".map2" / "config.json"
    pipewire_conf = (
        Path(args.pipewire_conf).expanduser()
        if args.pipewire_conf
        else target_home / ".config" / "pipewire" / "pipewire.conf.d" / "99-map2-audio-latency.conf"
    )
    systemd_dropin = None if args.no_systemd else Path(args.systemd_dropin).expanduser()
    return TargetPaths(config_file=config_file, pipewire_conf=pipewire_conf, systemd_dropin=systemd_dropin)


def _load_catalog(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Clock profile catalog not found: {path}")

    with path.open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle) or {}

    if not isinstance(payload, dict):
        raise ValueError(f"Clock profile catalog must be a mapping: {path}")
    if "profiles" not in payload or not isinstance(payload["profiles"], dict):
        raise ValueError(f"Clock profile catalog is missing 'profiles' mapping: {path}")

    return payload


def _json_clone(value: Any) -> Any:
    return json.loads(json.dumps(value))


def _load_existing_config(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"Config root must be a JSON object: {path}")
    return payload


def _ensure_parent(path: Path, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)


def _render_pipewire_conf(profile_name: str, profile: Dict[str, Any]) -> str:
    engine_rate = int(profile["engine_rate_hz"])
    buffer_size = int(profile["buffer_size_samples"])
    allowed_rates = " ".join(str(int(rate)) for rate in profile.get("allowed_rates_hz", [engine_rate]))

    return (
        "# MAP2 Audio Platform - Clock Sync Profile\n"
        f"# Profile: {profile_name}\n"
        "# REMARK: Generated by scripts/apply_clock_sync_profile.py\n"
        "# REMARK: Keep clock.force-* in systemd ExecStartPre; do NOT set force-* here.\n"
        "context.properties = {\n"
        f"    default.clock.rate = {engine_rate}\n"
        f"    default.clock.allowed-rates = [ {allowed_rates} ]\n"
        f"    default.clock.min-quantum = {buffer_size}\n"
        f"    default.clock.quantum = {buffer_size}\n"
        "    default.clock.max-quantum = 8192\n"
        "    api.alsa.period-num = 2\n"
        "    api.alsa.headroom = 0\n"
        "    mem.allow-mlock = true\n"
        "    mem.mlock-all = true\n"
        "}\n"
    )


def _render_systemd_dropin(profile_name: str, profile: Dict[str, Any]) -> str:
    engine_rate = int(profile["engine_rate_hz"])
    buffer_size = int(profile["buffer_size_samples"])

    return (
        "[Service]\n"
        f"# MAP2 clock sync profile: {profile_name}\n"
        "# REMARK: Generated by scripts/apply_clock_sync_profile.py\n"
        "# REMARK: rate MUST be applied before quantum (PipeWire resets quantum on rate change).\n"
        "ExecStartPre=\n"
        f"ExecStartPre=/usr/bin/pw-metadata -n settings 0 clock.force-rate {engine_rate}\n"
        f"ExecStartPre=/usr/bin/pw-metadata -n settings 0 clock.force-quantum {buffer_size}\n"
        f"Environment=\"PIPEWIRE_LATENCY={buffer_size}/{engine_rate}\"\n"
    )


def _ensure_dict_section(container: Dict[str, Any], key: str) -> Dict[str, Any]:
    current = container.get(key)
    if isinstance(current, dict):
        return current
    new_section: Dict[str, Any] = {}
    container[key] = new_section
    return new_section


def _build_config_update(
    existing_config: Dict[str, Any],
    *,
    profile_name: str,
    profile: Dict[str, Any],
    catalog_version: Any,
    avb_interface_override: str | None,
) -> Dict[str, Any]:
    config = copy.deepcopy(existing_config)

    audio = _ensure_dict_section(config, "audio")
    avb = _ensure_dict_section(config, "avb")
    spdif = _ensure_dict_section(config, "spdif")
    clock_sync = _ensure_dict_section(config, "clock_sync")
    avb_srp = _ensure_dict_section(avb, "srp")

    enabled_transports = [str(item).strip().lower() for item in profile.get("enabled_transports", [])]
    engine_rate = int(profile["engine_rate_hz"])
    avb_rate = int(profile["avb_stream_rate_hz"])
    spdif_rate = int(profile["spdif_rate_hz"])
    bits_per_sample = int(profile["bits_per_sample"])
    buffer_size = int(profile["buffer_size_samples"])
    allow_resampler = bool(profile.get("allow_resampler", False))
    require_hard_lock = bool(profile.get("require_hard_lock", True))
    remarks = [str(item) for item in profile.get("remarks", [])]
    allowed_rates = [int(rate) for rate in profile.get("allowed_rates_hz", [engine_rate])]

    audio["sample_rate"] = engine_rate
    audio["buffer_size"] = buffer_size
    audio["bits_per_sample"] = bits_per_sample
    audio["clock_master"] = str(profile.get("clock_master", "internal"))
    audio["sync_profile"] = profile_name
    audio["allowed_rates_hz"] = allowed_rates

    spdif["enabled"] = "spdif" in enabled_transports
    spdif["device"] = "Lexicon MPX1"
    spdif["sample_rate_hz"] = spdif_rate
    spdif["bits_per_sample"] = bits_per_sample
    spdif["allow_resampler"] = allow_resampler
    spdif["require_hard_lock"] = require_hard_lock
    spdif["transport_mode"] = "send_return"
    spdif["remarks"] = _json_clone(remarks)

    avb["enabled"] = bool(profile.get("avb_enabled", avb.get("enabled", False)))
    avb["auto_connect"] = bool(profile.get("avb_auto_connect", avb.get("auto_connect", False)))
    avb["ptp_priority1"] = int(profile.get("avb_ptp_priority1", avb.get("ptp_priority1", 128)))
    avb["stream_rate_hz"] = avb_rate
    avb["bits_per_sample"] = bits_per_sample
    avb["sample_rate_policy"] = "follow_clock_sync_profile"
    avb_srp["required"] = bool(profile.get("avb_srp_required", avb_srp.get("required", True)))
    if avb_interface_override:
        avb["interface"] = avb_interface_override

    clock_sync["selected_profile"] = profile_name
    clock_sync["profile_version"] = str(catalog_version or "")
    clock_sync["clock_master"] = str(profile.get("clock_master", "internal"))
    clock_sync["engine_rate_hz"] = engine_rate
    clock_sync["avb_stream_rate_hz"] = avb_rate
    clock_sync["spdif_rate_hz"] = spdif_rate
    clock_sync["bits_per_sample"] = bits_per_sample
    clock_sync["buffer_size_samples"] = buffer_size
    clock_sync["allowed_rates_hz"] = allowed_rates
    clock_sync["require_hard_lock"] = require_hard_lock
    clock_sync["allow_resampler"] = allow_resampler
    clock_sync["remarks"] = [
        "Generated by scripts/apply_clock_sync_profile.py.",
        "This is the canonical cross-transport bitrate mapping for future AI automation.",
        *remarks,
    ]

    return config


def _write_text(path: Path, content: str, dry_run: bool) -> None:
    _ensure_parent(path, dry_run=dry_run)
    if dry_run:
        return
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: Dict[str, Any], dry_run: bool) -> None:
    _ensure_parent(path, dry_run=dry_run)
    if dry_run:
        return
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=False)
        handle.write("\n")


def _format_profile_listing(profiles: Dict[str, Any]) -> str:
    lines: list[str] = []
    for name, payload in profiles.items():
        title = payload.get("title", name)
        summary = payload.get("summary", "")
        lines.append(f"- {name}: {title}")
        if summary:
            lines.append(f"    {summary}")
    return "\n".join(lines)


def _print_summary(
    *,
    profile_name: str,
    profile: Dict[str, Any],
    paths: TargetPaths,
    dry_run: bool,
    restart_backend: bool,
) -> None:
    summary = {
        "profile": profile_name,
        "clock_master": profile.get("clock_master"),
        "engine_rate_hz": profile.get("engine_rate_hz"),
        "spdif_rate_hz": profile.get("spdif_rate_hz"),
        "avb_stream_rate_hz": profile.get("avb_stream_rate_hz"),
        "bits_per_sample": profile.get("bits_per_sample"),
        "buffer_size_samples": profile.get("buffer_size_samples"),
        "allowed_rates_hz": profile.get("allowed_rates_hz"),
        "dry_run": dry_run,
        "config_file": str(paths.config_file),
        "pipewire_conf": str(paths.pipewire_conf),
        "systemd_dropin": str(paths.systemd_dropin) if paths.systemd_dropin else None,
        "restart_backend": restart_backend,
    }
    print(json.dumps(summary, indent=2))


def _restart_backend_if_requested(restart_backend: bool, dry_run: bool) -> None:
    if not restart_backend:
        return
    if dry_run:
        print("[dry-run] Would run: systemctl daemon-reload && systemctl restart map2-backend.service")
        return
    if os.geteuid() != 0:
        raise PermissionError(
            "--restart-backend requires root privileges (run via sudo or omit this flag)."
        )
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "restart", "map2-backend.service"], check=True)


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Apply MAP2 S/PDIF + AVB clock-sync profile mappings."
    )
    parser.add_argument(
        "--catalog",
        default=str(DEFAULT_PROFILE_CATALOG),
        help="Clock profile catalog YAML path (default: config/audio-clock-sync-profiles.yaml)",
    )
    parser.add_argument(
        "--list-profiles",
        action="store_true",
        help="Print available profile IDs and exit.",
    )
    parser.add_argument(
        "--profile",
        default="",
        help="Profile ID to apply (use --list-profiles to view choices).",
    )
    parser.add_argument(
        "--target-home",
        default="",
        help="Explicit target home directory for user-level config files.",
    )
    parser.add_argument(
        "--config-file",
        default="",
        help="Override MAP2 config JSON path (default: <target-home>/.map2/config.json).",
    )
    parser.add_argument(
        "--pipewire-conf",
        default="",
        help="Override PipeWire fragment path (default: <target-home>/.config/pipewire/pipewire.conf.d/99-map2-audio-latency.conf).",
    )
    parser.add_argument(
        "--systemd-dropin",
        default=str(DEFAULT_SYSTEMD_DROPIN),
        help="Override systemd drop-in path (default: /etc/systemd/system/map2-backend.service.d/20-clock-sync-profile.conf).",
    )
    parser.add_argument(
        "--no-systemd",
        action="store_true",
        help="Skip writing systemd drop-in file.",
    )
    parser.add_argument(
        "--avb-interface",
        default="",
        help="Optional AVB interface override to set in config (e.g. enp11s0).",
    )
    parser.add_argument(
        "--restart-backend",
        action="store_true",
        help="After write, run daemon-reload and restart map2-backend.service.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print summary without writing files.",
    )
    return parser.parse_args(list(argv))


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    catalog_path = Path(args.catalog).expanduser()
    catalog = _load_catalog(catalog_path)
    profiles = catalog["profiles"]

    if args.list_profiles:
        print(_format_profile_listing(profiles))
        return 0

    profile_name = str(args.profile).strip()
    if not profile_name:
        raise SystemExit("Missing --profile. Use --list-profiles to inspect options.")
    if profile_name not in profiles:
        raise SystemExit(
            f"Unknown profile '{profile_name}'. Use --list-profiles. "
            f"Available: {', '.join(sorted(profiles.keys()))}"
        )

    profile = profiles[profile_name]
    if not isinstance(profile, dict):
        raise SystemExit(f"Profile '{profile_name}' must be a mapping.")

    paths = _resolve_paths(args)
    existing_config = _load_existing_config(paths.config_file)
    merged_config = _build_config_update(
        existing_config,
        profile_name=profile_name,
        profile=profile,
        catalog_version=catalog.get("version"),
        avb_interface_override=(args.avb_interface or "").strip() or None,
    )

    pipewire_conf = _render_pipewire_conf(profile_name, profile)
    systemd_dropin = _render_systemd_dropin(profile_name, profile)

    _write_json(paths.config_file, merged_config, dry_run=args.dry_run)
    _write_text(paths.pipewire_conf, pipewire_conf, dry_run=args.dry_run)
    if paths.systemd_dropin is not None:
        _write_text(paths.systemd_dropin, systemd_dropin, dry_run=args.dry_run)

    _print_summary(
        profile_name=profile_name,
        profile=profile,
        paths=paths,
        dry_run=args.dry_run,
        restart_backend=args.restart_backend,
    )
    _restart_backend_if_requested(args.restart_backend, dry_run=args.dry_run)

    if args.dry_run:
        print("[dry-run] No files were modified.")
    else:
        print("Clock-sync profile applied successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
