#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  apply_avb_hil_matrix_update.sh <hil_summary_file> [matrix_file]

Arguments:
  hil_summary_file  Path to summary.txt generated by run_avb_hil_qualification.sh
  matrix_file       Qualification matrix file (default: docs/AVB_QUALIFICATION_MATRIX.md)

Result:
  Updates Q04/Q05/Q06 "Latest Outcome" and "Status" columns in-place.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

SUMMARY_FILE="${1:-}"
MATRIX_FILE="${2:-docs/AVB_QUALIFICATION_MATRIX.md}"

if [[ -z "$SUMMARY_FILE" ]]; then
  echo "ERROR: summary file is required." >&2
  usage
  exit 1
fi

if [[ ! -f "$SUMMARY_FILE" ]]; then
  echo "ERROR: summary file not found: $SUMMARY_FILE" >&2
  exit 1
fi

if [[ ! -f "$MATRIX_FILE" ]]; then
  echo "ERROR: matrix file not found: $MATRIX_FILE" >&2
  exit 1
fi

declare -A kv
while IFS='=' read -r key value; do
  [[ -z "$key" ]] && continue
  kv["$key"]="$value"
done < "$SUMMARY_FILE"

map_status() {
  local raw="$1"
  case "$raw" in
    PASS|FAIL|BLOCKED|PENDING)
      echo "$raw"
      ;;
    SKIPPED|"")
      echo "PENDING"
      ;;
    *)
      echo "PENDING"
      ;;
  esac
}

q04_status="$(map_status "${kv[q04_multi_node_discovery_route_churn]:-}")"
q05_status="$(map_status "${kv[q05_ptp_lock_transport_timing]:-}")"
q06_status="$(map_status "${kv[q06_24h_endurance_soak]:-}")"
q04_reason="${kv[q04_reason]:-}"
q05_reason="${kv[q05_reason]:-}"
q06_reason="${kv[q06_reason]:-}"

run_timestamp_utc="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
q04_log="${kv[q04_log]:-$SUMMARY_FILE}"
q05_log="${kv[q05_log]:-$SUMMARY_FILE}"
q06_log="${kv[q06_log]:-$SUMMARY_FILE}"

q04_outcome="HIL run ${run_timestamp_utc}; see ${q04_log}"
q05_outcome="HIL run ${run_timestamp_utc}; see ${q05_log}"
if [[ "$q04_status" == "BLOCKED" ]]; then
  q04_outcome="Blocked: ${q04_reason:-lab precondition missing}; see ${q04_log}"
fi
if [[ "$q05_status" == "BLOCKED" ]]; then
  q05_outcome="Blocked: ${q05_reason:-lab precondition missing}; see ${q05_log}"
fi
if [[ "${kv[q06_24h_endurance_soak]:-SKIPPED}" == "SKIPPED" ]]; then
  q06_outcome="Deferred in this run; see ${q06_log}"
else
  q06_outcome="HIL run ${run_timestamp_utc}; see ${q06_log}"
fi
if [[ "$q06_status" == "BLOCKED" ]]; then
  q06_outcome="Blocked: ${q06_reason:-lab precondition missing}; see ${q06_log}"
fi

tmp_file="${MATRIX_FILE}.tmp"
awk \
  -v q04_status="$q04_status" \
  -v q05_status="$q05_status" \
  -v q06_status="$q06_status" \
  -v q04_outcome="$q04_outcome" \
  -v q05_outcome="$q05_outcome" \
  -v q06_outcome="$q06_outcome" \
'
function trim(s) {
  gsub(/^[ \t]+/, "", s)
  gsub(/[ \t]+$/, "", s)
  return s
}
BEGIN { FS="|"; OFS="|" }
/^\| Q0[456] / {
  id = trim($2)
  if (id == "Q04") {
    $7 = " " q04_outcome " "
    $8 = " " q04_status " "
    print
    next
  }
  if (id == "Q05") {
    $7 = " " q05_outcome " "
    $8 = " " q05_status " "
    print
    next
  }
  if (id == "Q06") {
    $7 = " " q06_outcome " "
    $8 = " " q06_status " "
    print
    next
  }
}
{ print }
' "$MATRIX_FILE" > "$tmp_file"

mv "$tmp_file" "$MATRIX_FILE"
echo "Updated $MATRIX_FILE using $SUMMARY_FILE"
