#!/usr/bin/env python3
"""Run-14b cycle 2 — generate TypeScript types for the device-peak-meters
WebSocket frame envelope.

Reads the canonical Pydantic models in `app/services/devices/_meter_ws_schema.py`
and writes a hand-rolled TS module to `web/src/app/types/meterWsFrame.generated.ts`.
The TS module mirrors the Pydantic shapes verbatim so the frontend hooks
(useDeviceMeterSourceStream, useDevicesPeakMetersStream, etc.) can import
typed interfaces that stay in lockstep with the backend.

Modes:
  * --check  — exit non-zero if the generated file would change (CI gate)
  * default  — write the generated file in place

Why a standalone emitter (vs reusing openapi-typescript):
  * The meter-WS schema is small + closed (4 type variants, ~10 fields total)
  * No extra Node dep at codegen time — the existing snapshot codegen
    pattern uses openapi-typescript, but for this surface a Python emitter
    keeps the gen step self-contained and matches the schema module's
    Pydantic source exactly (no JSON Schema → TS interface translation
    drift)
  * Deterministic output — every run produces the same bytes, so the
    --check CI gate catches drift cleanly
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_PATH = REPO_ROOT / "web" / "src" / "app" / "types" / "meterWsFrame.generated.ts"


GENERATED_HEADER = """// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Matthew Mackes — MAP2 Audio Platform
//
// AUTO-GENERATED by `scripts/generate_meter_ws_types.py`. DO NOT EDIT.
//
// Source of truth: `app/services/devices/_meter_ws_schema.py`. Both sides
// share the same Pydantic models — this TS module mirrors the canonical
// shape so frontend hooks consuming the device-peak-meters WS streams
// (useDeviceMeterSourceStream, useDevicesPeakMetersStream,
// useDevicesPeakMetersClusterStream) get typed envelopes for free.
//
// To refresh after a schema change:
//   python3 scripts/generate_meter_ws_types.py
//
// CI invariant: `python3 scripts/generate_meter_ws_types.py --check`
// must exit 0 — drift between this file and the Pydantic source fails CI.
"""


def emit_typescript() -> str:
    """Emit the canonical TS module body. The Pydantic source is loaded
    via in-process import so the wire-level constants stay byte-identical
    (no JSON Schema round-trip)."""
    sys.path.insert(0, str(REPO_ROOT))
    # Import the canonical wire-protocol constants directly so the TS
    # literals match the Python literals exactly. If a future rename
    # changes either side, the import fails and the codegen step fails
    # loud (catches the drift before the file is written).
    from app.services.devices._meter_ws_schema import (
        CLUSTER_REGISTRY_FRAME_TYPE,
        REGISTRY_FRAME_TYPE,
        SCHEMA_VERSION,
    )

    return f"""{GENERATED_HEADER}

// ---------------------------------------------------------------------------
// Canonical wire-protocol constants (mirror app/services/devices/_meter_ws_schema.py)
// ---------------------------------------------------------------------------

export const REGISTRY_FRAME_TYPE = {REGISTRY_FRAME_TYPE!r} as const
export const CLUSTER_REGISTRY_FRAME_TYPE = {CLUSTER_REGISTRY_FRAME_TYPE!r} as const
export const SCHEMA_VERSION = {SCHEMA_VERSION} as const

export type MeterWsFrameType =
  | typeof REGISTRY_FRAME_TYPE
  | typeof CLUSTER_REGISTRY_FRAME_TYPE

// ---------------------------------------------------------------------------
// Per-snapshot models (shared between local + cluster frames)
// ---------------------------------------------------------------------------

/** `engine` = measured from the live engine ring buffer;
 *  `placeholder` = silence fallback (no measurement yet);
 *  `engine_unavailable` = engine source registered but its reader raised. */
export type MeterSourceKind = 'engine' | 'placeholder' | 'engine_unavailable'

/** Per-channel peak-dBFS snapshot for a single device. Pydantic source:
 *  `MeterSnapshotPayload`. */
export interface MeterSnapshotPayload {{
  input_peak_db: number[]
  output_peak_db: number[]
  source: MeterSourceKind
  /** Unix timestamp (seconds since epoch) when the source produced
   *  the snapshot. None when not stamped. */
  captured_at: number | null
}}

/** One device's slot in a registry frame's `data.devices[]` array.
 *  `snapshot` is null when the consumer didn't request inline snapshots
 *  (cluster registry default). */
export interface DeviceMeterRow {{
  device_id: string
  input_channels: number
  output_channels: number
  has_engine_source: boolean
  snapshot: MeterSnapshotPayload | null
}}

// ---------------------------------------------------------------------------
// Local registry frame (`device_peak_meters:registry`)
// ---------------------------------------------------------------------------

export interface DeviceMeterRegistryData {{
  devices: DeviceMeterRow[]
}}

/** Frame envelope emitted by `/api/v1/devices/peak-meters/stream`. */
export interface DeviceMeterRegistryFrame {{
  type: typeof REGISTRY_FRAME_TYPE
  schema_version: typeof SCHEMA_VERSION
  data: DeviceMeterRegistryData
}}

// ---------------------------------------------------------------------------
// Cluster registry frame (`device_peak_meters:cluster_registry`)
// ---------------------------------------------------------------------------

/** One peer's contribution to a cluster registry frame. */
export interface ClusterPeerSlice {{
  node_id: string
  hostname: string | null
  devices: DeviceMeterRow[]
  /** Sourced from NodeHealthService. One of: ok / warn / critical / offline. */
  health: string
  fetch_age_seconds: number | null
}}

export interface ClusterMeterRegistryData {{
  local: DeviceMeterRegistryData
  peers: ClusterPeerSlice[]
  /** Per-node error string keyed by node_id; `@local` reserved for the
   *  local node's own snapshot failure path. */
  errors: Record<string, string>
}}

/** Frame envelope emitted by `/api/v1/devices/peak-meters/cluster/stream`. */
export interface ClusterMeterRegistryFrame {{
  type: typeof CLUSTER_REGISTRY_FRAME_TYPE
  schema_version: typeof SCHEMA_VERSION
  data: ClusterMeterRegistryData
}}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

/** True iff `frame` is a non-null object with a recognized `type` value
 *  AND the canonical schema_version. Useful in the WS hook's onFrame
 *  callback as a cheap runtime check before narrowing. */
export function isRegistryFrame(frame: unknown): frame is DeviceMeterRegistryFrame {{
  if (typeof frame !== 'object' || frame === null) return false
  const f = frame as Record<string, unknown>
  return (
    f.type === REGISTRY_FRAME_TYPE &&
    f.schema_version === SCHEMA_VERSION &&
    typeof f.data === 'object' &&
    f.data !== null
  )
}}

export function isClusterRegistryFrame(frame: unknown): frame is ClusterMeterRegistryFrame {{
  if (typeof frame !== 'object' || frame === null) return false
  const f = frame as Record<string, unknown>
  return (
    f.type === CLUSTER_REGISTRY_FRAME_TYPE &&
    f.schema_version === SCHEMA_VERSION &&
    typeof f.data === 'object' &&
    f.data !== null
  )
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit nonzero if the generated file would change. CI gate.",
    )
    args = parser.parse_args()

    new_content = emit_typescript()
    GENERATED_PATH.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not GENERATED_PATH.exists():
            print(
                f"FAIL: {GENERATED_PATH} does not exist. Run "
                "`python3 scripts/generate_meter_ws_types.py` to generate it.",
                file=sys.stderr,
            )
            return 1
        existing = GENERATED_PATH.read_text()
        if existing != new_content:
            print(
                f"FAIL: {GENERATED_PATH} is out of date with the canonical "
                "Pydantic schema in app/services/devices/_meter_ws_schema.py. "
                "Run `python3 scripts/generate_meter_ws_types.py` to refresh.",
                file=sys.stderr,
            )
            return 1
        return 0

    GENERATED_PATH.write_text(new_content)
    print(f"OK: wrote {GENERATED_PATH} ({len(new_content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
