#!/usr/bin/env python3
"""Run-14c cycle 2 — TS codegen for the midi:traffic WS frame envelope.

Mirrors the meter-WS + sonobus-events codegens for the third platform
WS topic.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_PATH = (
    REPO_ROOT / "web" / "src" / "app" / "types" / "midiTrafficWsFrame.generated.ts"
)


GENERATED_HEADER = """// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Matthew Mackes — MAP2 Audio Platform
//
// AUTO-GENERATED by `scripts/generate_midi_traffic_ws_types.py`. DO NOT EDIT.
//
// Source of truth: `app/services/midi_hub/_traffic_ws_schema.py`.
//
// To refresh after a schema change:
//   python3 scripts/generate_midi_traffic_ws_types.py
//
// CI invariant: `python3 scripts/generate_midi_traffic_ws_types.py --check`
// must exit 0.
"""


def emit_typescript() -> str:
    sys.path.insert(0, str(REPO_ROOT))
    from app.services.midi_hub._traffic_ws_schema import (
        SCHEMA_VERSION,
        TRAFFIC_FRAME_TYPE,
    )

    return f"""{GENERATED_HEADER}

// ---------------------------------------------------------------------------
// Canonical wire-protocol constants
// ---------------------------------------------------------------------------

export const MIDI_TRAFFIC_FRAME_TYPE = {TRAFFIC_FRAME_TYPE!r} as const
export const MIDI_TRAFFIC_SCHEMA_VERSION = {SCHEMA_VERSION} as const

// ---------------------------------------------------------------------------
// Decoded MIDI message body
// ---------------------------------------------------------------------------

/** Standard MIDI message types. Open string union so future parser
 *  extensions don't bump the canonical schema. */
export type MidiMessageType =
  | 'note_on'
  | 'note_off'
  | 'polypressure'
  | 'cc'
  | 'program'
  | 'aftertouch'
  | 'pitchbend'
  | 'system'
  | string

export interface DecodedMidiMessage {{
  message_type: MidiMessageType
  /** MIDI channel (0-15). */
  channel: number
  data1: number
  data2: number
}}

// ---------------------------------------------------------------------------
// Traffic payload (the `data` field of the WS frame)
// ---------------------------------------------------------------------------

/** Direction discriminator. Inbound = raw arrival; outbound = post-route. */
export type MidiTrafficDirection = 'inbound' | 'outbound'

export interface MidiTrafficPayload {{
  /** Capture time in ns (monotonic-relative time.time_ns()). */
  timestamp_ns: number
  source_port: string
  /** Empty string for raw-inbound events. */
  destination_port: string
  direction: MidiTrafficDirection
  /** Route ID for outbound events; null for inbound. */
  route_id: string | null
  /** Raw MIDI bytes hex-encoded (e.g. "90 3c 7f"). */
  raw_hex: string
  decoded: DecodedMidiMessage
}}

// ---------------------------------------------------------------------------
// Frame envelope
// ---------------------------------------------------------------------------

export interface MidiTrafficFrame {{
  type: typeof MIDI_TRAFFIC_FRAME_TYPE
  /** Defaults to 1 in the legacy emitter (no schema_version field) so
   *  the field is optional in the type — present + correct in newer
   *  emissions, possibly missing in legacy ones. */
  schema_version?: number
  data: MidiTrafficPayload
}}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

export function isMidiTrafficFrame(frame: unknown): frame is MidiTrafficFrame {{
  if (typeof frame !== 'object' || frame === null) return false
  const f = frame as Record<string, unknown>
  return (
    f.type === MIDI_TRAFFIC_FRAME_TYPE &&
    typeof f.data === 'object' &&
    f.data !== null
  )
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    new_content = emit_typescript()
    GENERATED_PATH.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not GENERATED_PATH.exists():
            print(
                f"FAIL: {GENERATED_PATH} does not exist. Run "
                "`python3 scripts/generate_midi_traffic_ws_types.py` to generate it.",
                file=sys.stderr,
            )
            return 1
        if GENERATED_PATH.read_text() != new_content:
            print(
                f"FAIL: {GENERATED_PATH} is out of date with the canonical "
                "Pydantic schema in app/services/midi_hub/_traffic_ws_schema.py. "
                "Run `python3 scripts/generate_midi_traffic_ws_types.py` to refresh.",
                file=sys.stderr,
            )
            return 1
        return 0

    GENERATED_PATH.write_text(new_content)
    print(f"OK: wrote {GENERATED_PATH} ({len(new_content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
