#!/usr/bin/env python3
"""Render OS-level branding artifacts from the brand manifest.

Reads ``branding/brand.manifest.json`` (layered with
``~/.map2/brand.manifest.override.json`` if present) and produces the
artifacts consumed by ``scripts/install_branding.sh`` and the systemd
rewriter. Idempotent and dry-run capable.

Outputs:
  - branding/generated/branding.env  (shell env sourced by login/welcome scripts)
  - branding/generated/login-issue.txt  (rendered preview, non-authoritative)

Authoritative templates already exist as shell scripts under branding/; this
renderer only produces the env file so the scripts pick up the manifest's
values without anyone editing the scripts themselves.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "branding" / "brand.manifest.json"
OVERRIDE = Path(os.path.expanduser("~/.map2/brand.manifest.override.json"))
OUT_DIR = REPO_ROOT / "branding" / "generated"


def _deep_merge(base: dict[str, Any], patch: dict[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for k, v in patch.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def load_manifest() -> dict[str, Any]:
    if not MANIFEST.exists():
        raise SystemExit(f"manifest missing: {MANIFEST}")
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if OVERRIDE.exists():
        try:
            patch = json.loads(OVERRIDE.read_text(encoding="utf-8"))
            data = _deep_merge(data, patch)
        except Exception as exc:
            print(f"warning: ignoring corrupt override: {exc}", file=sys.stderr)
    return data


def _shell_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_env(m: dict[str, Any]) -> str:
    copy = m.get("copy", {}) or {}
    lines = [
        "# Generated by scripts/render_branding_templates.py — do not edit by hand.",
        f'MAP2_LOGIN_ISSUE_PRODUCT_NAME={_shell_quote(m.get("productName", ""))}',
        f'MAP2_BRAND_SHORT_NAME={_shell_quote(m.get("shortName", ""))}',
        f'MAP2_BRAND_TAGLINE={_shell_quote(m.get("tagline", ""))}',
        f'MAP2_BRAND_VENDOR={_shell_quote(m.get("vendor", ""))}',
        f'MAP2_BRAND_WELCOME_HEADLINE={_shell_quote(copy.get("welcomeHeadline", ""))}',
        f'MAP2_BRAND_WELCOME_SUBLINE={_shell_quote(copy.get("welcomeSubline", ""))}',
        f'MAP2_BRAND_LOGIN_BANNER={_shell_quote(copy.get("loginBanner", ""))}',
        f'MAP2_BRAND_SYSTEMD_PREFIX={_shell_quote(copy.get("systemdPrefix", ""))}',
    ]
    return "\n".join(lines) + "\n"


def render_login_preview(m: dict[str, Any]) -> str:
    copy = m.get("copy", {}) or {}
    hostname = os.uname().nodename
    banner = (copy.get("loginBanner") or "").replace("{hostname}", hostname)
    return (
        f"{m.get('productName', '')}\n"
        f"{m.get('tagline', '')}\n"
        f"{banner}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dry-run", action="store_true", help="print outputs without writing")
    args = ap.parse_args()

    manifest = load_manifest()
    env_text = render_env(manifest)
    preview_text = render_login_preview(manifest)

    if args.dry_run:
        print("== branding.env ==")
        print(env_text)
        print("== login-issue.txt ==")
        print(preview_text)
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "branding.env").write_text(env_text, encoding="utf-8")
    (OUT_DIR / "login-issue.txt").write_text(preview_text, encoding="utf-8")
    print(f"wrote {OUT_DIR / 'branding.env'}")
    print(f"wrote {OUT_DIR / 'login-issue.txt'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
