#!/usr/bin/env python3
"""Sync `device-packs/_mixx-imports/` from upstream Mixxx.

T2459-E5. Periodic operator-run script to refresh the imported corpus
when new Mixxx mappings ship upstream.

Workflow:

  python3 scripts/sync_mixxx_imports.py /path/to/mixxx-clone

Steps:

  1. Read the upstream commit hash from the user-supplied Mixxx clone.
  2. Mirror `<mixxx>/res/controllers/` into
     `device-packs/_mixx-imports/res/controllers/`.
  3. Update `device-packs/_mixx-imports/MANIFEST.yaml` with the new
     commit + import date.
  4. Regenerate `device-packs/_mixx-imports/IMPORT_CHECKSUMS.txt` so
     the immutability test can verify the corpus going forward.

Operator must:
  - Pull the desired Mixxx commit into the source clone first.
  - Review the resulting diff before committing.

This script does not push, commit, or modify anything outside
`device-packs/_mixx-imports/`.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
IMPORTS_ROOT = REPO_ROOT / "device-packs" / "_mixx-imports"
CONTROLLERS_DEST = IMPORTS_ROOT / "res" / "controllers"
MANIFEST_PATH = IMPORTS_ROOT / "MANIFEST.yaml"
CHECKSUMS_PATH = IMPORTS_ROOT / "IMPORT_CHECKSUMS.txt"


def _git_commit_hash(repo: Path) -> str:
    out = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo), capture_output=True, text=True, check=True,
    )
    return out.stdout.strip()


def _checksum_corpus(root: Path) -> dict[str, str]:
    """SHA-256 every file under `root`, keyed by repo-relative path."""
    sums: dict[str, str] = {}
    if not root.is_dir():
        return sums
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        # Skip MAP2-mutable sidecars.
        if p.name.endswith(".MAP2.yaml"):
            continue
        rel = p.relative_to(REPO_ROOT)
        h = hashlib.sha256(p.read_bytes()).hexdigest()
        sums[str(rel)] = h
    return sums


def _write_checksum_file(sums: dict[str, str]) -> None:
    lines = [
        "# Auto-generated by scripts/sync_mixxx_imports.py — do not edit by hand.",
        "# Each line: <sha256>  <relative-path>",
        "# Used by tests/test_mixxx_imports_immutable.py to verify no",
        "# Mixxx-attributed file has been edited in-place.",
        "",
    ]
    for rel, h in sorted(sums.items()):
        lines.append(f"{h}  {rel}")
    CHECKSUMS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "mixxx_clone",
        help="Path to a local Mixxx git clone at the desired commit.",
    )
    parser.add_argument(
        "--checksum-only", action="store_true",
        help="Only regenerate IMPORT_CHECKSUMS.txt; don't copy any files.",
    )
    args = parser.parse_args(argv)

    if args.checksum_only:
        sums = _checksum_corpus(IMPORTS_ROOT)
        _write_checksum_file(sums)
        print(f"Wrote {len(sums)} checksums to {CHECKSUMS_PATH}")
        return 0

    src = Path(args.mixxx_clone) / "res" / "controllers"
    if not src.is_dir():
        print(f"ERROR: {src} does not exist", file=sys.stderr)
        return 2

    commit = _git_commit_hash(Path(args.mixxx_clone))
    print(f"Importing from {src} (upstream commit {commit})")

    # Wipe + remirror.
    if CONTROLLERS_DEST.exists():
        shutil.rmtree(CONTROLLERS_DEST)
    CONTROLLERS_DEST.mkdir(parents=True)
    for entry in src.iterdir():
        target = CONTROLLERS_DEST / entry.name
        if entry.is_dir():
            shutil.copytree(entry, target)
        else:
            shutil.copy2(entry, target)
    print(f"Copied {sum(1 for _ in CONTROLLERS_DEST.rglob('*') if _.is_file())} files")

    # Refresh manifest.
    today = date.today().isoformat()
    if MANIFEST_PATH.exists():
        text = MANIFEST_PATH.read_text(encoding="utf-8")
        # Best-effort line replacement; the manifest is authored by hand so
        # we patch the two header fields without rewriting the doc body.
        new_lines = []
        for line in text.splitlines():
            if line.startswith("upstream_commit:"):
                new_lines.append(f"upstream_commit: {commit}")
            elif line.startswith("imported_at:"):
                new_lines.append(f"imported_at: '{today}'")
            else:
                new_lines.append(line)
        MANIFEST_PATH.write_text("\n".join(new_lines) + "\n", encoding="utf-8")

    # Refresh checksums.
    sums = _checksum_corpus(IMPORTS_ROOT)
    _write_checksum_file(sums)
    print(f"Wrote {len(sums)} checksums.")
    print("Review the diff and commit when ready.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
