// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Matthew Mackes — MAP2 Audio Platform
//
// AUTO-GENERATED by `scripts/generate_meter_ws_types.py`. DO NOT EDIT.
//
// Source of truth: `app/services/devices/_meter_ws_schema.py`. Both sides
// share the same Pydantic models — this TS module mirrors the canonical
// shape so frontend hooks consuming the device-peak-meters WS streams
// (useDeviceMeterSourceStream, useDevicesPeakMetersStream,
// useDevicesPeakMetersClusterStream) get typed envelopes for free.
//
// To refresh after a schema change:
//   python3 scripts/generate_meter_ws_types.py
//
// CI invariant: `python3 scripts/generate_meter_ws_types.py --check`
// must exit 0 — drift between this file and the Pydantic source fails CI.


// ---------------------------------------------------------------------------
// Canonical wire-protocol constants (mirror app/services/devices/_meter_ws_schema.py)
// ---------------------------------------------------------------------------

export const REGISTRY_FRAME_TYPE = 'device_peak_meters:registry' as const
export const CLUSTER_REGISTRY_FRAME_TYPE = 'device_peak_meters:cluster_registry' as const
export const SCHEMA_VERSION = 1 as const

export type MeterWsFrameType =
  | typeof REGISTRY_FRAME_TYPE
  | typeof CLUSTER_REGISTRY_FRAME_TYPE

// ---------------------------------------------------------------------------
// Per-snapshot models (shared between local + cluster frames)
// ---------------------------------------------------------------------------

/** `engine` = measured from the live engine ring buffer;
 *  `placeholder` = silence fallback (no measurement yet);
 *  `engine_unavailable` = engine source registered but its reader raised. */
export type MeterSourceKind = 'engine' | 'placeholder' | 'engine_unavailable'

/** Per-channel peak-dBFS snapshot for a single device. Pydantic source:
 *  `MeterSnapshotPayload`. */
export interface MeterSnapshotPayload {
  input_peak_db: number[]
  output_peak_db: number[]
  source: MeterSourceKind
  /** Unix timestamp (seconds since epoch) when the source produced
   *  the snapshot. None when not stamped. */
  captured_at: number | null
}

/** One device's slot in a registry frame's `data.devices[]` array.
 *  `snapshot` is null when the consumer didn't request inline snapshots
 *  (cluster registry default). */
export interface DeviceMeterRow {
  device_id: string
  input_channels: number
  output_channels: number
  has_engine_source: boolean
  snapshot: MeterSnapshotPayload | null
}

// ---------------------------------------------------------------------------
// Local registry frame (`device_peak_meters:registry`)
// ---------------------------------------------------------------------------

export interface DeviceMeterRegistryData {
  devices: DeviceMeterRow[]
}

/** Frame envelope emitted by `/api/v1/devices/peak-meters/stream`. */
export interface DeviceMeterRegistryFrame {
  type: typeof REGISTRY_FRAME_TYPE
  schema_version: typeof SCHEMA_VERSION
  data: DeviceMeterRegistryData
}

// ---------------------------------------------------------------------------
// Cluster registry frame (`device_peak_meters:cluster_registry`)
// ---------------------------------------------------------------------------

/** One peer's contribution to a cluster registry frame. */
export interface ClusterPeerSlice {
  node_id: string
  hostname: string | null
  devices: DeviceMeterRow[]
  /** Sourced from NodeHealthService. One of: ok / warn / critical / offline. */
  health: string
  fetch_age_seconds: number | null
}

export interface ClusterMeterRegistryData {
  local: DeviceMeterRegistryData
  peers: ClusterPeerSlice[]
  /** Per-node error string keyed by node_id; `@local` reserved for the
   *  local node's own snapshot failure path. */
  errors: Record<string, string>
}

/** Frame envelope emitted by `/api/v1/devices/peak-meters/cluster/stream`. */
export interface ClusterMeterRegistryFrame {
  type: typeof CLUSTER_REGISTRY_FRAME_TYPE
  schema_version: typeof SCHEMA_VERSION
  data: ClusterMeterRegistryData
}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

/** True iff `frame` is a non-null object with a recognized `type` value
 *  AND the canonical schema_version. Useful in the WS hook's onFrame
 *  callback as a cheap runtime check before narrowing. */
export function isRegistryFrame(frame: unknown): frame is DeviceMeterRegistryFrame {
  if (typeof frame !== 'object' || frame === null) return false
  const f = frame as Record<string, unknown>
  return (
    f.type === REGISTRY_FRAME_TYPE &&
    f.schema_version === SCHEMA_VERSION &&
    typeof f.data === 'object' &&
    f.data !== null
  )
}

export function isClusterRegistryFrame(frame: unknown): frame is ClusterMeterRegistryFrame {
  if (typeof frame !== 'object' || frame === null) return false
  const f = frame as Record<string, unknown>
  return (
    f.type === CLUSTER_REGISTRY_FRAME_TYPE &&
    f.schema_version === SCHEMA_VERSION &&
    typeof f.data === 'object' &&
    f.data !== null
  )
}
