// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Matthew Mackes — MAP2 Audio Platform
//
// AUTO-GENERATED by `scripts/generate_midi_traffic_ws_types.py`. DO NOT EDIT.
//
// Source of truth: `app/services/midi_hub/_traffic_ws_schema.py`.
//
// To refresh after a schema change:
//   python3 scripts/generate_midi_traffic_ws_types.py
//
// CI invariant: `python3 scripts/generate_midi_traffic_ws_types.py --check`
// must exit 0.


// ---------------------------------------------------------------------------
// Canonical wire-protocol constants
// ---------------------------------------------------------------------------

export const MIDI_TRAFFIC_FRAME_TYPE = 'midi:traffic' as const
export const MIDI_TRAFFIC_SCHEMA_VERSION = 1 as const

// ---------------------------------------------------------------------------
// Decoded MIDI message body
// ---------------------------------------------------------------------------

/** Standard MIDI message types. Open string union so future parser
 *  extensions don't bump the canonical schema. */
export type MidiMessageType =
  | 'note_on'
  | 'note_off'
  | 'polypressure'
  | 'cc'
  | 'program'
  | 'aftertouch'
  | 'pitchbend'
  | 'system'
  | string

export interface DecodedMidiMessage {
  message_type: MidiMessageType
  /** MIDI channel (0-15). */
  channel: number
  data1: number
  data2: number
}

// ---------------------------------------------------------------------------
// Traffic payload (the `data` field of the WS frame)
// ---------------------------------------------------------------------------

/** Direction discriminator. Inbound = raw arrival; outbound = post-route. */
export type MidiTrafficDirection = 'inbound' | 'outbound'

export interface MidiTrafficPayload {
  /** Capture time in ns (monotonic-relative time.time_ns()). */
  timestamp_ns: number
  source_port: string
  /** Empty string for raw-inbound events. */
  destination_port: string
  direction: MidiTrafficDirection
  /** Route ID for outbound events; null for inbound. */
  route_id: string | null
  /** Raw MIDI bytes hex-encoded (e.g. "90 3c 7f"). */
  raw_hex: string
  decoded: DecodedMidiMessage
}

// ---------------------------------------------------------------------------
// Frame envelope
// ---------------------------------------------------------------------------

export interface MidiTrafficFrame {
  type: typeof MIDI_TRAFFIC_FRAME_TYPE
  /** Defaults to 1 in the legacy emitter (no schema_version field) so
   *  the field is optional in the type — present + correct in newer
   *  emissions, possibly missing in legacy ones. */
  schema_version?: number
  data: MidiTrafficPayload
}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

export function isMidiTrafficFrame(frame: unknown): frame is MidiTrafficFrame {
  if (typeof frame !== 'object' || frame === null) return false
  const f = frame as Record<string, unknown>
  return (
    f.type === MIDI_TRAFFIC_FRAME_TYPE &&
    typeof f.data === 'object' &&
    f.data !== null
  )
}
