// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Matthew Mackes — MAP2 Audio Platform
//
// AUTO-GENERATED by `scripts/generate_sonobus_events_ws_types.py`. DO NOT EDIT.
//
// Source of truth: `app/services/sonobus/_events_ws_schema.py`. Frontend
// consumers of the `/api/sonobus/events` WS stream import typed envelopes
// from this module so a backend schema change cannot drift silently.
//
// To refresh after a schema change:
//   python3 scripts/generate_sonobus_events_ws_types.py
//
// CI invariant: `python3 scripts/generate_sonobus_events_ws_types.py --check`
// must exit 0 — drift between this file and the Pydantic source fails CI.


// ---------------------------------------------------------------------------
// Canonical wire-protocol constants
// ---------------------------------------------------------------------------

export const SONOBUS_STATE_FRAME_TYPE = 'sonobus:state' as const
export const SONOBUS_HEARTBEAT_FRAME_TYPE = 'sonobus:heartbeat' as const
export const SONOBUS_DAEMON_EVENT_FRAME_TYPE = 'sonobus:daemon' as const
export const SONOBUS_EVENTS_SCHEMA_VERSION = 1 as const

export type SonoBusEventsFrameType =
  | typeof SONOBUS_STATE_FRAME_TYPE
  | typeof SONOBUS_HEARTBEAT_FRAME_TYPE
  | typeof SONOBUS_DAEMON_EVENT_FRAME_TYPE

// ---------------------------------------------------------------------------
// State/heartbeat body (shared between sonobus:state + sonobus:heartbeat)
// ---------------------------------------------------------------------------

/** Canonical supervisor state string. Mirrors
 *  `app/services/sonobus/daemon_supervisor.py::SonoBusDaemonStatus`. */
export type SonoBusDaemonStatusString =
  | 'stopped'
  | 'waiting-for-binary'
  | 'waiting-for-daemon'
  | 'connecting'
  | 'running'
  | 'reconnecting'
  | 'degraded'
  | 'shutdown'

/** Body of `sonobus:state` + `sonobus:heartbeat` frames. */
export interface SonoBusStatusSnapshot {
  authority_ok: boolean
  /** Set only when authority_ok=false; carries the exception message. */
  error: string | null
  binding_count: number
  enabled_binding_count: number
  /** ISO-8601 wall-clock when this snapshot was taken. */
  timestamp: string
  /** True iff the supervisor is connected to the daemon UDS. */
  daemon_running: boolean
  daemon_endpoint: string | null
  daemon_status: SonoBusDaemonStatusString | string
  /** Full daemon hello-handshake snapshot when connected. */
  daemon_capabilities: Record<string, unknown> | null
}

// ---------------------------------------------------------------------------
// State + heartbeat frame envelopes
// ---------------------------------------------------------------------------

export interface SonoBusStateFrame {
  type: typeof SONOBUS_STATE_FRAME_TYPE
  schema_version: typeof SONOBUS_EVENTS_SCHEMA_VERSION
  data: SonoBusStatusSnapshot
}

export interface SonoBusHeartbeatFrame {
  type: typeof SONOBUS_HEARTBEAT_FRAME_TYPE
  schema_version: typeof SONOBUS_EVENTS_SCHEMA_VERSION
  data: SonoBusStatusSnapshot
}

// ---------------------------------------------------------------------------
// Daemon event frame envelope
// ---------------------------------------------------------------------------

/** The inner body of a `sonobus:daemon` frame. Wraps one async event
 *  forwarded from the daemon supervisor's events queue. */
export interface SonoBusDaemonEventBody {
  /** Daemon event type. One of: peer_up / peer_down / session_start /
   *  session_stop / metrics_snapshot / transport_error / unknown. */
  type: string
  event: true
  payload: Record<string, unknown>
}

export interface SonoBusDaemonEventFrame {
  type: typeof SONOBUS_DAEMON_EVENT_FRAME_TYPE
  schema_version: typeof SONOBUS_EVENTS_SCHEMA_VERSION
  data: SonoBusDaemonEventBody
}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

function _isCanonicalEnvelope(frame: unknown, expectedType: string): boolean {
  if (typeof frame !== 'object' || frame === null) return false
  const f = frame as Record<string, unknown>
  return (
    f.type === expectedType &&
    f.schema_version === SONOBUS_EVENTS_SCHEMA_VERSION &&
    typeof f.data === 'object' &&
    f.data !== null
  )
}

export function isSonoBusStateFrame(frame: unknown): frame is SonoBusStateFrame {
  return _isCanonicalEnvelope(frame, SONOBUS_STATE_FRAME_TYPE)
}

export function isSonoBusHeartbeatFrame(frame: unknown): frame is SonoBusHeartbeatFrame {
  return _isCanonicalEnvelope(frame, SONOBUS_HEARTBEAT_FRAME_TYPE)
}

export function isSonoBusDaemonEventFrame(frame: unknown): frame is SonoBusDaemonEventFrame {
  return _isCanonicalEnvelope(frame, SONOBUS_DAEMON_EVENT_FRAME_TYPE)
}

/** Discriminated-union guard: returns the frame's topic if it's one of
 *  the canonical three, or null otherwise. Useful when a single WS
 *  subscription handles all three frame topics. */
export function classifySonoBusFrame(
  frame: unknown,
): SonoBusEventsFrameType | null {
  if (isSonoBusStateFrame(frame)) return SONOBUS_STATE_FRAME_TYPE
  if (isSonoBusHeartbeatFrame(frame)) return SONOBUS_HEARTBEAT_FRAME_TYPE
  if (isSonoBusDaemonEventFrame(frame)) return SONOBUS_DAEMON_EVENT_FRAME_TYPE
  return null
}
