from __future__ import annotations

SYSEX_NUM_BYTES = 16567
NUM_DEVICES = 8
NUM_PRESETS = 200
NUM_PEDALS = 2
NUM_GCX = 4
NUM_GCX_LOOPS = 8
NUM_GCX_SWITCHES = 8
NUM_INSTANT_ACCESS = 8

PREAMBLE = bytes([0xF0, 0x00, 0x00, 0x07, 0x10])
TERMINATOR = bytes([0xF7])

CONFIG_NUM_BYTES = 161
PRESET_NUM_BYTES = 82

DEVICE_NAME_LENGTH = 8
PRESET_NAME_LENGTH = 10

CONFIG_OFFSET = len(PREAMBLE)
PRESET_OFFSET = CONFIG_OFFSET + CONFIG_NUM_BYTES
TERMINATOR_OFFSET = PRESET_OFFSET + (PRESET_NUM_BYTES * NUM_PRESETS)

SOFT_OPTION_GLOBAL_PROGRAM_MASK = 0x01
SOFT_OPTION_LINK_MODE_MASK = 0x0C
SOFT_OPTION_LINK_MODE_SHIFT = 2
SOFT_OPTION_RESPOND_MASK = 0x40
SOFT_OPTION_RESPOND_SHIFT = 6

PROFILE_ID = "v1_13_bulk_dump"
