apiVersion: 1

deleteDatasources:
  - name: MAP2 Prometheus
    orgId: 1

datasources:
  - name: MAP2 Prometheus
    uid: map2-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
